In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
pd.set_option('display.max_columns', None)

import numpy as np

# 데이터로드: 6년치+구동+중분류 합치기

## 데이터 로드

### 자치구행정동

In [ ]:
# 자치구행정동 상권코드 데이터 로드
seoul_gudong = pd.read_csv('/content/drive/MyDrive/MC_KDT/프로젝트/파이널프로젝트/데이터/상권코드_preprocessed.csv', encoding='utf-8')
seoul_gudong

          순번  자치구          행정동    상권_코드                     상권명  상권분류   면적(m²)
0        1.0  용산구        이태원1동  1001491                이태원 관광특구  관광특구   392647
1        2.0   중구          소공동  1001492  명동 남대문 북창동 다동 무교동 관광특구  관광특구   928278
2        3.0   중구          광희동  1001493            동대문패션타운 관광특구  관광특구   610708
3        4.0  종로구  종로1.2.3.4가동  1001494              종로·청계 관광특구  관광특구   635586
4        5.0  송파구          오륜동  1001495                 잠실 관광특구  관광특구  2334402
...      ...  ...          ...      ...                     ...   ...      ...
1666  1667.0  강동구         천호3동  2130322                고분다리전통시장  전통시장    31695
1667  1668.0  강동구         성내3동  2130323                 둔촌역전통시장  전통시장    36519
1668  1669.0  강동구           길동  2130324                 길동복조리시장  전통시장    29606
1669  1670.0  강동구         명일1동  2130325                  명일전통시장  전통시장    27660
1670  1671.0  강동구         고덕2동  2130326               고덕 골목형상점가  전통시장    29846

[1671 rows x 7 columns]

### 업종정보

In [ ]:
# 업종 정보 데이터 로드
category = pd.read_excel('/content/drive/MyDrive/MC_KDT/프로젝트/파이널프로젝트/데이터/업종코드_중분류.xlsx')
category

   대분류      중분류     업종명  Unnamed: 3  Unnamed: 4
0   외식      식사류   한식음식점         NaN         NaN
1   외식      식사류   중식음식점         NaN         NaN
2   외식      식사류   일식음식점         NaN         NaN
3   외식      식사류   양식음식점         NaN         NaN
4   외식  카페/베이커리     제과점         NaN         NaN
..  ..      ...     ...         ...         ...
94  소매  가구/인테리어    인테리어         NaN         NaN
95  소매  가구/인테리어    조명용품         NaN         NaN
96  소매  가구/인테리어     예술품         NaN         NaN
97  소매       주유     주유소         NaN         NaN
98  소매       유통  전자상거래업         NaN         NaN

[99 rows x 5 columns]

### 매출_상권

In [ ]:
# 매출 데이터 로드
sales_2022 = pd.read_csv('/content/drive/MyDrive/MC_KDT/프로젝트/파이널프로젝트/데이터/서울시 상권분석서비스(상권-추정매출)_2022년.csv', encoding='cp949')
sales_2021 = pd.read_csv('/content/drive/MyDrive/MC_KDT/프로젝트/파이널프로젝트/데이터/서울시_우리마을가게_상권분석서비스(신_상권_추정매출)_2021년.csv', encoding='cp949')
sales_2020 = pd.read_csv('/content/drive/MyDrive/MC_KDT/프로젝트/파이널프로젝트/데이터/서울시_우리마을가게_상권분석서비스(신_상권_추정매출)_2020년.csv', encoding='cp949')
sales_2019 = pd.read_csv('/content/drive/MyDrive/MC_KDT/프로젝트/파이널프로젝트/데이터/서울시_우리마을가게_상권분석서비스(신_상권_추정매출)_2019년.csv', encoding='cp949')
sales_2018 = pd.read_csv('/content/drive/MyDrive/MC_KDT/프로젝트/파이널프로젝트/데이터/서울시_우리마을가게_상권분석서비스(신_상권_추정매출)_2018년.csv', encoding = 'cp949')
sales_2017 = pd.read_csv('/content/drive/MyDrive/MC_KDT/프로젝트/파이널프로젝트/데이터/서울시_우리마을가게_상권분석서비스(신_상권_추정매출)_2017년.csv', encoding = 'cp949')

In [ ]:
# 매출 데이터 로드 결과 확인
sales_2017.head(1)

,기준_년_코드,기준_분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,분기당_매출_금액,분기당_매출_건수,주중_매출_비율,주말_매출_비율,월요일_매출_비율,화요일_매출_비율,수요일_매출_비율,목요일_매출_비율,금요일_매출_비율,토요일_매출_비율,일요일_매출_비율,시간대_00~06_매출_비율,시간대_06~11_매출_비율,시간대_11~14_매출_비율,시간대_14~17_매출_비율,시간대_17~21_매출_비율,시간대_21~24_매출_비율,남성_매출_비율,여성_매출_비율,연령대_10_매출_비율,연령대_20_매출_비율,연령대_30_매출_비율,연령대_40_매출_비율,연령대_50_매출_비율,연령대_60_이상_매출_비율,주중_매출_금액,주말_매출_금액,월요일_매출_금액,화요일_매출_금액,수요일_매출_금액,목요일_매출_금액,금요일_매출_금액,토요일_매출_금액,일요일_매출_금액,시간대_00~06_매출_금액,시간대_06~11_매출_금액,시간대_11~14_매출_금액,시간대_14~17_매출_금액,시간대_17~21_매출_금액,시간대_21~24_매출_금액,남성_매출_금액,여성_매출_금액,연령대_10_매출_금액,연령대_20_매출_금액,연령대_30_매출_금액,연령대_40_매출_금액,연령대_50_매출_금액,연령대_60_이상_매출_금액,주중_매출_건수,주말_매출_건수,월요일_매출_건수,화요일_매출_건수,수요일_매출_건수,목요일_매출_건수,금요일_매출_건수,토요일_매출_건수,일요일_매출_건수,시간대_건수~06_매출_건수,시간대_건수~11_매출_건수,시간대_건수~14_매출_건수,시간대_건수~17_매출_건수,시간대_건수~21_매출_건수,시간대_건수~24_매출_건수,남성_매출_건수,여성_매출_건수,연령대_10_매출_건수,연령대_20_매출_건수,연령대_30_매출_건수,연령대_40_매출_건수,연령대_50_매출_건수,연령대_60_이상_매출_건수,점포수
0,2017,1,A,골목상권,2110001,이북5도청사,CS100001,한식음식점,816890247,28082,61,39,12,12,13,12,12,20,19,0,6,34,20,33,7,69,31,0,4,11,23,33,29,497915307,318974940,95800777,95212641,107801237,97573067,101527585,163389524,155585416,1931173,50530078,280342732,159126641,271871706,53087917,402187424,177217247,1674112,21859757,62806246,134016633,191828274,167219653,18996,9086,3618,3575,4026,3855,3922,4212,4874,62,2559,11878,4674,7765,1144,15424,6832,152,1308,2807,5298,6917,5776,27

### 점포_상권

In [ ]:
# 점포 데이터_상권 로드
store_2022 = pd.read_csv('/content/drive/MyDrive/MC_KDT/프로젝트/파이널프로젝트/데이터/서울시 상권분석서비스(상권-점포)_2022년.csv', encoding='cp949')
store_2021 = pd.read_csv('/content/drive/MyDrive/MC_KDT/프로젝트/파이널프로젝트/데이터/서울시_우리마을가게_상권분석서비스(신_상권_점포)_2021년.csv', encoding='cp949')
store_2020 = pd.read_csv('/content/drive/MyDrive/MC_KDT/프로젝트/파이널프로젝트/데이터/서울시_우리마을가게_상권분석서비스(신_상권_점포)_2020년.csv', encoding='cp949')
store_2019 = pd.read_csv('/content/drive/MyDrive/MC_KDT/프로젝트/파이널프로젝트/데이터/서울시_우리마을가게_상권분석서비스(신_상권_점포)_2019년.csv', encoding='cp949')
store_2018 = pd.read_csv('/content/drive/MyDrive/MC_KDT/프로젝트/파이널프로젝트/데이터/서울시_우리마을가게_상권분석서비스(신_상권_점포)_2018년.csv', encoding='cp949')
store_2017 = pd.read_csv('/content/drive/MyDrive/MC_KDT/프로젝트/파이널프로젝트/데이터/서울시_우리마을가게_상권분석서비스(신_상권_점포)_2017년.csv', encoding='cp949')

In [ ]:
# 점포 데이터_상권 로드 결과 확인
store_2022.head(2)

,기준_년_코드,기준_분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,점포_수,유사_업종_점포_수,개업_율,개업_점포_수,폐업_률,폐업_점포_수,프랜차이즈_점포_수
0,2022,4,U,관광특구,1001496,강남 마이스 관광특구,CS300043,전자상거래업,6,6,0,0,0,0,0
1,2022,4,U,관광특구,1001496,강남 마이스 관광특구,CS300042,주유소,1,1,0,0,0,0,0

### 점포_상권배후지

In [ ]:
# 점포 데이터_상권배후지 로드
hinterland_2022 = pd.read_csv('/content/drive/MyDrive/MC_KDT/프로젝트/파이널프로젝트/데이터/서울시 상권분석서비스(상권배후지-점포)_2022년.csv', encoding='cp949')
hinterland_2021 = pd.read_csv('/content/drive/MyDrive/MC_KDT/프로젝트/파이널프로젝트/데이터/서울시_우리마을가게_상권분석서비스(신_상권배후지_점포)_2021년.csv', encoding='cp949')
hinterland_2020 = pd.read_csv('/content/drive/MyDrive/MC_KDT/프로젝트/파이널프로젝트/데이터/서울시_우리마을가게_상권분석서비스(신_상권배후지_점포)_2020년.csv', encoding='cp949')
hinterland_2019 = pd.read_csv('/content/drive/MyDrive/MC_KDT/프로젝트/파이널프로젝트/데이터/서울시_우리마을가게_상권분석서비스(신_상권배후지_점포)_2019년.csv', encoding='cp949')
hinterland_2018 = pd.read_csv('/content/drive/MyDrive/MC_KDT/프로젝트/파이널프로젝트/데이터/서울시_우리마을가게_상권분석서비스(신_상권배후지_점포)_2018년.csv', encoding='cp949')
hinterland_2017 = pd.read_csv('/content/drive/MyDrive/MC_KDT/프로젝트/파이널프로젝트/데이터/서울시_우리마을가게_상권분석서비스(신_상권배후지_점포)_2017년.csv', encoding='cp949')

hinterland_2017.head(2)

,기준_년_코드,기준_분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,점포_수,유사_업종_점포_수,개업_율,개업_점포_수,폐업_률,폐업_점포_수,프랜차이즈_점포_수
0,2017,1,A,골목상권,2110001,이북5도청사,CS100001,한식음식점,27,29,3,1,3,1,2
1,2017,1,A,골목상권,2110001,이북5도청사,CS100002,중식음식점,0,1,0,0,0,0,1

In [ ]:
# 데이터 확인용 --> ex. '상권_코드'가 2110001 경우 뭐가 나오나
check_test = hinterland_2017[hinterland_2017['상권_코드'] == 2110001]

check_test

,기준_년_코드,기준_분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,점포_수,유사_업종_점포_수,개업_율,개업_점포_수,폐업_률,폐업_점포_수,프랜차이즈_점포_수
0,2017,1,A,골목상권,2110001,이북5도청사,CS100001,한식음식점,27,29,3,1,3,1,2
1,2017,1,A,골목상권,2110001,이북5도청사,CS100002,중식음식점,0,1,0,0,0,0,1
2,2017,1,A,골목상권,2110001,이북5도청사,CS100003,일식음식점,2,2,0,0,0,0,0
3,2017,1,A,골목상권,2110001,이북5도청사,CS100004,양식음식점,4,4,0,0,0,0,0
4,2017,1,A,골목상권,2110001,이북5도청사,CS100005,제과점,0,1,0,0,100,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259350,2017,4,A,골목상권,2110001,이북5도청사,CS300031,가구,2,2,0,0,0,0,0
259351,2017,4,A,골목상권,2110001,이북5도청사,CS300035,인테리어,2,2,0,0,0,0,0
259352,2017,4,A,골목상권,2110001,이북5도청사,CS300036,조명용품,3,3,0,0,0,0,0
259353,2017,4,A,골목상권,2110001,이북5도청사,CS300041,예술품,1,1,0,0,0,0,0
259354,2017,4,A,골목상권,2110001,이북5도청사,CS300043,전자상거래업,2,2,0,0,0,0,0

In [ ]:
# 점포 데이터_상권배후지 로드 결과 확인

## 6년치 합치기

### 점포데이터_상권

In [ ]:
# 점포 데이터 컬럼 확인 ==> 모두 연도 데이터셋의 컬럼 일치 확인
print("■■■■2022 점포 컬럼\n", store_2022.columns)
print("■■■■2021 점포 컬럼\n", store_2021.columns)
print("■■■■2020 점포 컬럼\n", store_2020.columns)
print("■■■■2019 점포 컬럼\n", store_2019.columns)
print("■■■■2018 점포 컬럼\n", store_2018.columns)
print("■■■■2017 점포 컬럼\n", store_2017.columns)

■■■■2022 점포 컬럼
 Index(['기준_년_코드', '기준_분기_코드', '상권_구분_코드', '상권_구분_코드_명', '상권_코드', '상권_코드_명',
       '서비스_업종_코드', '서비스_업종_코드_명', '점포_수', '유사_업종_점포_수', '개업_율', '개업_점포_수',
       '폐업_률', '폐업_점포_수', '프랜차이즈_점포_수'],
      dtype='object')
■■■■2021 점포 컬럼
 Index(['기준_년_코드', '기준_분기_코드', '상권_구분_코드', '상권_구분_코드_명', '상권_코드', '상권_코드_명',
       '서비스_업종_코드', '서비스_업종_코드_명', '점포_수', '유사_업종_점포_수', '개업_율', '개업_점포_수',
       '폐업_률', '폐업_점포_수', '프랜차이즈_점포_수'],
      dtype='object')
■■■■2020 점포 컬럼
 Index(['기준_년_코드', '기준_분기_코드', '상권_구분_코드', '상권_구분_코드_명', '상권_코드', '상권_코드_명',
       '서비스_업종_코드', '서비스_업종_코드_명', '점포_수', '유사_업종_점포_수', '개업_율', '개업_점포_수',
       '폐업_률', '폐업_점포_수', '프랜차이즈_점포_수'],
      dtype='object')
■■■■2019 점포 컬럼
 Index(['기준_년_코드', '기준_분기_코드', '상권_구분_코드', '상권_구분_코드_명', '상권_코드', '상권_코드_명',
       '서비스_업종_코드', '서비스_업종_코드_명', '점포_수', '유사_업종_점포_수', '개업_율', '개업_점포_수',
       '폐업_률', '폐업_점포_수', '프랜차이즈_점포_수'],
      dtype='object')
■■■■2018 점포 컬럼
 Index(['기준_년_코드', '기준_분기_코드', '상권_구분_코드', '상권_구분_코드_명', '상권_코드', '상권_코드_명',
       '서비스_업종_코드', '서비스_업종_코드_명', '점포_수', '유사_업종_점포_수', '개업_율', '개업_점포_수',
       '폐업_률', '폐업_점포_수', '프랜차이즈_점포_수'],
      dtype='object')
■■■■2017 점포 컬럼
 Index(['기준_년_코드', '기준_분기_코드', '상권_구분_코드', '상권_구분_코드_명', '상권_코드', '상권_코드_명',
       '서비스_업종_코드', '서비스_업종_코드_명', '점포_수', '유사_업종_점포_수', '개업_율', '개업_점포_수',
       '폐업_률', '폐업_점포_수', '프랜차이즈_점포_수'],
      dtype='object')

In [ ]:
### 점포 데이터 6개년 합치기
dfs = [store_2022, store_2021, store_2020, store_2019, store_2018, store_2017]
store_6years = pd.concat(dfs, ignore_index=True)
store_6years

,기준_년_코드,기준_분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,점포_수,유사_업종_점포_수,개업_율,개업_점포_수,폐업_률,폐업_점포_수,프랜차이즈_점포_수
0,2022,4,U,관광특구,1001496,강남 마이스 관광특구,CS300043,전자상거래업,6,6,0,0,0,0,0
1,2022,4,U,관광특구,1001496,강남 마이스 관광특구,CS300042,주유소,1,1,0,0,0,0,0
2,2022,4,U,관광특구,1001496,강남 마이스 관광특구,CS300041,예술품,10,10,0,0,0,0,0
3,2022,4,U,관광특구,1001496,강남 마이스 관광특구,CS300038,자동차부품,10,10,0,0,0,0,0
4,2022,4,U,관광특구,1001496,강남 마이스 관광특구,CS300036,조명용품,14,14,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1787962,2017,4,U,관광특구,1001496,강남 마이스 관광특구,CS300036,조명용품,12,12,0,0,0,0,0
1787963,2017,4,U,관광특구,1001496,강남 마이스 관광특구,CS300038,자동차부품,10,10,0,0,0,0,0
1787964,2017,4,U,관광특구,1001496,강남 마이스 관광특구,CS300041,예술품,9,9,0,0,0,0,0
1787965,2017,4,U,관광특구,1001496,강남 마이스 관광특구,CS300042,주유소,1,1,0,0,0,0,0
1787966,2017,4,U,관광특구,1001496,강남 마이스 관광특구,CS300043,전자상거래업,8,8,0,0,0,0,0

### 점포데이터_상권배후지

In [ ]:
# 점포_배후지 데이터 컬럼 확인 ==> 모든 연도가 동일 컬럼임을 확인함
print("▶▶▶▶2022 점포_배후지 컬럼\n", hinterland_2022.columns)
print("▶▶▶▶2021 점포_배후지 컬럼\n", hinterland_2021.columns)
print("▶▶▶▶2020 점포_배후지 컬럼\n", hinterland_2020.columns)
print("▶▶▶▶2019 점포_배후지 컬럼\n", hinterland_2019.columns)
print("▶▶▶▶2018 점포_배후지 컬럼\n", hinterland_2018.columns)
print("▶▶▶▶2017 점포_배후지 컬럼\n", hinterland_2017.columns)

▶▶▶▶2022 점포_배후지 컬럼
 Index(['기준_년_코드', '기준_분기_코드', '상권_구분_코드', '상권_구분_코드_명', '상권_코드', '상권_코드_명',
       '서비스_업종_코드', '서비스_업종_코드_명', '점포_수', '유사_업종_점포_수', '개업_율', '개업_점포_수',
       '폐업_률', '폐업_점포_수', '프랜차이즈_점포_수'],
      dtype='object')
▶▶▶▶2021 점포_배후지 컬럼
 Index(['기준_년_코드', '기준_분기_코드', '상권_구분_코드', '상권_구분_코드_명', '상권_코드', '상권_코드_명',
       '서비스_업종_코드', '서비스_업종_코드_명', '점포_수', '유사_업종_점포_수', '개업_율', '개업_점포_수',
       '폐업_률', '폐업_점포_수', '프랜차이즈_점포_수'],
      dtype='object')
▶▶▶▶2020 점포_배후지 컬럼
 Index(['기준_년_코드', '기준_분기_코드', '상권_구분_코드', '상권_구분_코드_명', '상권_코드', '상권_코드_명',
       '서비스_업종_코드', '서비스_업종_코드_명', '점포_수', '유사_업종_점포_수', '개업_율', '개업_점포_수',
       '폐업_률', '폐업_점포_수', '프랜차이즈_점포_수'],
      dtype='object')
▶▶▶▶2019 점포_배후지 컬럼
 Index(['기준_년_코드', '기준_분기_코드', '상권_구분_코드', '상권_구분_코드_명', '상권_코드', '상권_코드_명',
       '서비스_업종_코드', '서비스_업종_코드_명', '점포_수', '유사_업종_점포_수', '개업_율', '개업_점포_수',
       '폐업_률', '폐업_점포_수', '프랜차이즈_점포_수'],
      dtype='object')
▶▶▶▶2018 점포_배후지 컬럼
 Index(['기준_년_코드', '기준_분기_코드', '상권_구분_코드', '상권_구분_코드_명', '상권_코드', '상권_코드_명',
       '서비스_업종_코드', '서비스_업종_코드_명', '점포_수', '유사_업종_점포_수', '개업_율', '개업_점포_수',
       '폐업_률', '폐업_점포_수', '프랜차이즈_점포_수'],
      dtype='object')
▶▶▶▶2017 점포_배후지 컬럼
 Index(['기준_년_코드', '기준_분기_코드', '상권_구분_코드', '상권_구분_코드_명', '상권_코드', '상권_코드_명',
       '서비스_업종_코드', '서비스_업종_코드_명', '점포_수', '유사_업종_점포_수', '개업_율', '개업_점포_수',
       '폐업_률', '폐업_점포_수', '프랜차이즈_점포_수'],
      dtype='object')

In [ ]:
### 6개년 합치기

dfs = [hinterland_2022, hinterland_2021, hinterland_2020, hinterland_2019, hinterland_2018, hinterland_2017]

hinterland_6years = pd.concat(dfs, ignore_index=True)
hinterland_6years = hinterland_6years.sort_values(by=['기준_년_코드', '기준_분기_코드'], ascending=[False, True])
hinterland_6years.reset_index(drop=True, inplace=True)
hinterland_6years

,기준_년_코드,기준_분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,점포_수,유사_업종_점포_수,개업_율,개업_점포_수,폐업_률,폐업_점포_수,프랜차이즈_점포_수
0,2022,1,A,골목상권,2111090,강일동주민센터,CS300043,전자상거래업,6,6,0,0,0,0,0
1,2022,1,A,골목상권,2111090,강일동주민센터,CS300038,자동차부품,2,2,0,0,0,0,0
2,2022,1,A,골목상권,2111090,강일동주민센터,CS300036,조명용품,1,1,0,0,0,0,0
3,2022,1,A,골목상권,2111090,강일동주민센터,CS300035,인테리어,1,1,0,0,0,0,0
4,2022,1,A,골목상권,2111090,강일동주민센터,CS300034,악기,1,1,100,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2073897,2017,4,A,골목상권,2111090,강일동주민센터,CS300029,애완동물,1,1,0,0,0,0,0
2073898,2017,4,A,골목상권,2111090,강일동주민센터,CS300032,가전제품,1,1,0,0,0,0,0
2073899,2017,4,A,골목상권,2111090,강일동주민센터,CS300036,조명용품,1,1,0,0,0,0,0
2073900,2017,4,A,골목상권,2111090,강일동주민센터,CS300038,자동차부품,1,1,0,0,0,0,0
2073901,2017,4,A,골목상권,2111090,강일동주민센터,CS300043,전자상거래업,7,7,0,0,0,0,0

In [ ]:
hinterland_6years = hinterland_6years.rename(columns = {'유사_업종_점포_수':'배후지_총점포수', '점포_수':'배후지_점포수', '개업_점포_수':'배후지_개업점포수', '폐업_점포_수':'배후지_폐업점포수',
                                                        '프랜차이즈_점포_수':'배후지_프랜차이즈점포수'})
hinterland_6years.head(2)

,기준_년_코드,기준_분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,배후지_점포수,배후지_총점포수,개업_율,배후지_개업점포수,폐업_률,배후지_폐업점포수,배후지_프랜차이즈점포수
0,2022,1,A,골목상권,2111090,강일동주민센터,CS300043,전자상거래업,6,6,0,0,0,0,0
1,2022,1,A,골목상권,2111090,강일동주민센터,CS300038,자동차부품,2,2,0,0,0,0,0

In [ ]:
hinterland_6years.columns

Index(['기준_년_코드', '기준_분기_코드', '상권_구분_코드', '상권_구분_코드_명', '상권_코드', '상권_코드_명',
       '서비스_업종_코드', '서비스_업종_코드_명', '배후지_점포수', '배후지_총점포수', '개업_율', '배후지_개업점포수',
       '폐업_률', '배후지_폐업점포수', '배후지_프랜차이즈점포수'],
      dtype='object')

In [ ]:
# '상권_코드' 열의 값이 2110804 '서비스_업종_코드' 열의 값이 'CS200003'인 행 추출
target_row = hinterland_6years[(hinterland_6years['상권_코드'] == 2110804) & (hinterland_6years['서비스_업종_코드'] == 'CS200003')]
target_row

,기준_년_코드,기준_분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,점포_수,유사_업종_점포_수,개업_율,개업_점포_수,폐업_률,폐업_점포_수,프랜차이즈_점포_수
22946,2022,1,A,골목상권,2110804,신풍역 1번,CS200003,예술학원,24,25,4,1,0,0,1
109262,2022,2,A,골목상권,2110804,신풍역 1번,CS200003,예술학원,24,25,4,1,0,0,1
195576,2022,3,A,골목상권,2110804,신풍역 1번,CS200003,예술학원,24,25,0,0,0,0,1
281912,2022,4,A,골목상권,2110804,신풍역 1번,CS200003,예술학원,24,25,0,0,0,0,1
408722,2021,1,A,골목상권,2110804,신풍역 1번,CS200003,예술학원,21,22,5,1,0,0,1
495127,2021,2,A,골목상권,2110804,신풍역 1번,CS200003,예술학원,22,23,4,1,0,0,1
581500,2021,3,A,골목상권,2110804,신풍역 1번,CS200003,예술학원,22,23,0,0,0,0,1
667873,2021,4,A,골목상권,2110804,신풍역 1번,CS200003,예술학원,23,24,4,1,0,0,1
754445,2020,1,A,골목상권,2110804,신풍역 1번,CS200003,예술학원,19,20,0,0,5,1,1
841017,2020,2,A,골목상권,2110804,신풍역 1번,CS200003,예술학원,19,20,0,0,0,0,1
927535,2020,3,A,골목상권,2110804,신풍역 1번,CS200003,예술학원,19,20,10,2,10,2,1
1014019,2020,4,A,골목상권,2110804,신풍역 1번,CS200003,예술학원,20,21,5,1,0,0,1
1100388,2019,1,A,골목상권,2110804,신풍역 1번,CS200003,예술학원,17,17,0,0,0,0,0
1186738,2019,2,A,골목상권,2110804,신풍역 1번,CS200003,예술학원,17,17,0,0,0,0,0
1273077,2019,3,A,골목상권,2110804,신풍역 1번,CS200003,예술학원,18,19,11,2,0,0,1
1359389,2019,4,A,골목상권,2110804,신풍역 1번,CS200003,예술학원,19,20,5,1,0,0,1
1445857,2018,1,A,골목상권,2110804,신풍역 1번,CS200003,예술학원,17,17,0,0,0,0,0
1532296,2018,2,A,골목상권,2110804,신풍역 1번,CS200003,예술학원,17,17,0,0,0,0,0
1618705,2018,3,A,골목상권,2110804,신풍역 1번,CS200003,예술학원,17,17,6,1,6,1,0
1705123,2018,4,A,골목상권,2110804,신풍역 1번,CS200003,예술학원,17,17,0,0,0,0,0
1791583,2017,1,A,골목상권,2110804,신풍역 1번,CS200003,예술학원,18,18,6,1,0,0,0
1877990,2017,2,A,골목상권,2110804,신풍역 1번,CS200003,예술학원,18,18,0,0,0,0,0
1964458,2017,3,A,골목상권,2110804,신풍역 1번,CS200003,예술학원,18,18,0,0,0,0,0
2050936,2017,4,A,골목상권,2110804,신풍역 1번,CS200003,예술학원,17,17,0,0,6,1,0

### 매출데이터

In [ ]:
# 매출 데이터 컬럼 확인 ==> 모든 연도가 동일 컬럼임을 확인함
print("▶▶▶▶2022 매출 컬럼\n", sales_2022.columns)
print("▶▶▶▶2021 매출 컬럼\n", sales_2021.columns)
print("▶▶▶▶2020 매출 컬럼\n", sales_2020.columns)
print("▶▶▶▶2019 매출 컬럼\n", sales_2019.columns)
print("▶▶▶▶2018 매출 컬럼\n", sales_2018.columns)
print("▶▶▶▶2017 매출 컬럼\n", sales_2017.columns)

▶▶▶▶2022 매출 컬럼
 Index(['기준_년_코드', '기준_분기_코드', '상권_구분_코드', '상권_구분_코드_명', '상권_코드', '상권_코드_명',
       '서비스_업종_코드', '서비스_업종_코드_명', '분기당_매출_금액', '분기당_매출_건수', '주중_매출_비율',
       '주말_매출_비율', '월요일_매출_비율', '화요일_매출_비율', '수요일_매출_비율', '목요일_매출_비율',
       '금요일_매출_비율', '토요일_매출_비율', '일요일_매출_비율', '시간대_00~06_매출_비율',
       '시간대_06~11_매출_비율', '시간대_11~14_매출_비율', '시간대_14~17_매출_비율',
       '시간대_17~21_매출_비율', '시간대_21~24_매출_비율', '남성_매출_비율', '여성_매출_비율',
       '연령대_10_매출_비율', '연령대_20_매출_비율', '연령대_30_매출_비율', '연령대_40_매출_비율',
       '연령대_50_매출_비율', '연령대_60_이상_매출_비율', '주중_매출_금액', '주말_매출_금액', '월요일_매출_금액',
       '화요일_매출_금액', '수요일_매출_금액', '목요일_매출_금액', '금요일_매출_금액', '토요일_매출_금액',
       '일요일_매출_금액', '시간대_00~06_매출_금액', '시간대_06~11_매출_금액', '시간대_11~14_매출_금액',
       '시간대_14~17_매출_금액', '시간대_17~21_매출_금액', '시간대_21~24_매출_금액', '남성_매출_금액',
       '여성_매출_금액', '연령대_10_매출_금액', '연령대_20_매출_금액', '연령대_30_매출_금액',
       '연령대_40_매출_금액', '연령대_50_매출_금액', '연령대_60_이상_매출_금액', '주중_매출_건수',
       '주말_매출_건수', '월요일_매출_건수', '화요일_매출_건수', '수요일_매출_건수', '목요일_매출_건수',
       '금요일_매출_건수', '토요일_매출_건수', '일요일_매출_건수', '시간대_건수~06_매출_건수',
       '시간대_건수~11_매출_건수', '시간대_건수~14_매출_건수', '시간대_건수~17_매출_건수',
       '시간대_건수~21_매출_건수', '시간대_건수~24_매출_건수', '남성_매출_건수', '여성_매출_건수',
       '연령대_10_매출_건수', '연령대_20_매출_건수', '연령대_30_매출_건수', '연령대_40_매출_건수',
       '연령대_50_매출_건수', '연령대_60_이상_매출_건수', '점포수'],
      dtype='object')
▶▶▶▶2021 매출 컬럼
 Index(['기준_년_코드', '기준_분기_코드', '상권_구분_코드', '상권_구분_코드_명', '상권_코드', '상권_코드_명',
       '서비스_업종_코드', '서비스_업종_코드_명', '분기당_매출_금액', '분기당_매출_건수', '주중_매출_비율',
       '주말_매출_비율', '월요일_매출_비율', '화요일_매출_비율', '수요일_매출_비율', '목요일_매출_비율',
       '금요일_매출_비율', '토요일_매출_비율', '일요일_매출_비율', '시간대_00~06_매출_비율',
       '시간대_06~11_매출_비율', '시간대_11~14_매출_비율', '시간대_14~17_매출_비율',
       '시간대_17~21_매출_비율', '시간대_21~24_매출_비율', '남성_매출_비율', '여성_매출_비율',
       '연령대_10_매출_비율', '연령대_20_매출_비율', '연령대_30_매출_비율', '연령대_40_매출_비율',
       '연령대_50_매출_비율', '연령대_60_이상_매출_비율', '주중_매출_금액', '주말_매출_금액', '월요일_매출_금액',
       '화요일_매출_금액', '수요일_매출_금액', '목요일_매출_금액', '금요일_매출_금액', '토요일_매출_금액',
       '일요일_매출_금액', '시간대_00~06_매출_금액', '시간대_06~11_매출_금액', '시간대_11~14_매출_금액',
       '시간대_14~17_매출_금액', '시간대_17~21_매출_금액', '시간대_21~24_매출_금액', '남성_매출_금액',
       '여성_매출_금액', '연령대_10_매출_금액', '연령대_20_매출_금액', '연령대_30_매출_금액',
       '연령대_40_매출_금액', '연령대_50_매출_금액', '연령대_60_이상_매출_금액', '주중_매출_건수',
       '주말_매출_건수', '월요일_매출_건수', '화요일_매출_건수', '수요일_매출_건수', '목요일_매출_건수',
       '금요일_매출_건수', '토요일_매출_건수', '일요일_매출_건수', '시간대_건수~06_매출_건수',
       '시간대_건수~11_매출_건수', '시간대_건수~14_매출_건수', '시간대_건수~17_매출_건수',
       '시간대_건수~21_매출_건수', '시간대_건수~24_매출_건수', '남성_매출_건수', '여성_매출_건수',
       '연령대_10_매출_건수', '연령대_20_매출_건수', '연령대_30_매출_건수', '연령대_40_매출_건수',
       '연령대_50_매출_건수', '연령대_60_이상_매출_건수', '점포수'],
      dtype='object')
▶▶▶▶2020 매출 컬럼
 Index(['기준_년_코드', '기준_분기_코드', '상권_구분_코드', '상권_구분_코드_명', '상권_코드', '상권_코드_명',
       '서비스_업종_코드', '서비스_업종_코드_명', '분기당_매출_금액', '분기당_매출_건수', '주중_매출_비율',
       '주말_매출_비율', '월요일_매출_비율', '화요일_매출_비율', '수요일_매출_비율', '목요일_매출_비율',
       '금요일_매출_비율', '토요일_매출_비율', '일요일_매출_비율', '시간대_00~06_매출_비율',
       '시간대_06~11_매출_비율', '시간대_11~14_매출_비율', '시간대_14~17_매출_비율',
       '시간대_17~21_매출_비율', '시간대_21~24_매출_비율', '남성_매출_비율', '여성_매출_비율',
       '연령대_10_매출_비율', '연령대_20_매출_비율', '연령대_30_매출_비율', '연령대_40_매출_비율',
       '연령대_50_매출_비율', '연령대_60_이상_매출_비율', '주중_매출_금액', '주말_매출_금액', '월요일_매출_금액',
       '화요일_매출_금액', '수요일_매출_금액', '목요일_매출_금액', '금요일_매출_금액', '토요일_매출_금액',
       '일요일_매출_금액', '시간대_00~06_매출_금액', '시간대_06~11_매출_금액', '시간대_11~14_매출_금액',
       '시간대_14~17_매출_금액', '시간대_17~21_매출_금액', '시간대_21~24_매출_금액', '남성_매출_금액',
       '여성_매출_금액', '연령대_10_매출_금액', '연령대_20_매출_금액', '연령대_30_매출_금액',
       '연령대_40_매출_금액', '연령대_50_매출_금액', '연령대_60_이상_매출_금액', '주중_매출_건수',
       '주말_매출_건수', '월요일_매출_건수', '화요일_매출_건수', '수요일_매출_건수', '목요일_매출_건수',
       '금요일_매출_건수', '토요일_매출_건수', '일요일_매출_건수', '시간대_건수~06_매출_건수',
       '시간대_건수~11_매출_건수', '시간대_건수~14_매출_건수', '시간대_건수~17_매출_건수',
       '시간대_건수~21_매출_건수', '시간대_건수~24_매출_건수', '남성_매출_건수', '여성_매출_건수',
       '연령대_10_매출_건수', '연령대_20_매출_건수', '연령대_30_매출_건수', '연령대_40_매출_건수',
       '연령대_50_매출_건수', '연령대_60_이상_매출_건수', '점포수'],
      dtype='object')
▶▶▶▶2019 매출 컬럼
 Index(['기준_년_코드', '기준_분기_코드', '상권_구분_코드', '상권_구분_코드_명', '상권_코드', '상권_코드_명',
       '서비스_업종_코드', '서비스_업종_코드_명', '분기당_매출_금액', '분기당_매출_건수', '주중_매출_비율',
       '주말_매출_비율', '월요일_매출_비율', '화요일_매출_비율', '수요일_매출_비율', '목요일_매출_비율',
       '금요일_매출_비율', '토요일_매출_비율', '일요일_매출_비율', '시간대_00~06_매출_비율',
       '시간대_06~11_매출_비율', '시간대_11~14_매출_비율', '시간대_14~17_매출_비율',
       '시간대_17~21_매출_비율', '시간대_21~24_매출_비율', '남성_매출_비율', '여성_매출_비율',
       '연령대_10_매출_비율', '연령대_20_매출_비율', '연령대_30_매출_비율', '연령대_40_매출_비율',
       '연령대_50_매출_비율', '연령대_60_이상_매출_비율', '주중_매출_금액', '주말_매출_금액', '월요일_매출_금액',
       '화요일_매출_금액', '수요일_매출_금액', '목요일_매출_금액', '금요일_매출_금액', '토요일_매출_금액',
       '일요일_매출_금액', '시간대_00~06_매출_금액', '시간대_06~11_매출_금액', '시간대_11~14_매출_금액',
       '시간대_14~17_매출_금액', '시간대_17~21_매출_금액', '시간대_21~24_매출_금액', '남성_매출_금액',
       '여성_매출_금액', '연령대_10_매출_금액', '연령대_20_매출_금액', '연령대_30_매출_금액',
       '연령대_40_매출_금액', '연령대_50_매출_금액', '연령대_60_이상_매출_금액', '주중_매출_건수',
       '주말_매출_건수', '월요일_매출_건수', '화요일_매출_건수', '수요일_매출_건수', '목요일_매출_건수',
       '금요일_매출_건수', '토요일_매출_건수', '일요일_매출_건수', '시간대_건수~06_매출_건수',
       '시간대_건수~11_매출_건수', '시간대_건수~14_매출_건수', '시간대_건수~17_매출_건수',
       '시간대_건수~21_매출_건수', '시간대_건수~24_매출_건수', '남성_매출_건수', '여성_매출_건수',
       '연령대_10_매출_건수', '연령대_20_매출_건수', '연령대_30_매출_건수', '연령대_40_매출_건수',
       '연령대_50_매출_건수', '연령대_60_이상_매출_건수', '점포수'],
      dtype='object')
▶▶▶▶2018 매출 컬럼
 Index(['기준_년_코드', '기준_분기_코드', '상권_구분_코드', '상권_구분_코드_명', '상권_코드', '상권_코드_명',
       '서비스_업종_코드', '서비스_업종_코드_명', '분기당_매출_금액', '분기당_매출_건수', '주중_매출_비율',
       '주말_매출_비율', '월요일_매출_비율', '화요일_매출_비율', '수요일_매출_비율', '목요일_매출_비율',
       '금요일_매출_비율', '토요일_매출_비율', '일요일_매출_비율', '시간대_00~06_매출_비율',
       '시간대_06~11_매출_비율', '시간대_11~14_매출_비율', '시간대_14~17_매출_비율',
       '시간대_17~21_매출_비율', '시간대_21~24_매출_비율', '남성_매출_비율', '여성_매출_비율',
       '연령대_10_매출_비율', '연령대_20_매출_비율', '연령대_30_매출_비율', '연령대_40_매출_비율',
       '연령대_50_매출_비율', '연령대_60_이상_매출_비율', '주중_매출_금액', '주말_매출_금액', '월요일_매출_금액',
       '화요일_매출_금액', '수요일_매출_금액', '목요일_매출_금액', '금요일_매출_금액', '토요일_매출_금액',
       '일요일_매출_금액', '시간대_00~06_매출_금액', '시간대_06~11_매출_금액', '시간대_11~14_매출_금액',
       '시간대_14~17_매출_금액', '시간대_17~21_매출_금액', '시간대_21~24_매출_금액', '남성_매출_금액',
       '여성_매출_금액', '연령대_10_매출_금액', '연령대_20_매출_금액', '연령대_30_매출_금액',
       '연령대_40_매출_금액', '연령대_50_매출_금액', '연령대_60_이상_매출_금액', '주중_매출_건수',
       '주말_매출_건수', '월요일_매출_건수', '화요일_매출_건수', '수요일_매출_건수', '목요일_매출_건수',
       '금요일_매출_건수', '토요일_매출_건수', '일요일_매출_건수', '시간대_건수~06_매출_건수',
       '시간대_건수~11_매출_건수', '시간대_건수~14_매출_건수', '시간대_건수~17_매출_건수',
       '시간대_건수~21_매출_건수', '시간대_건수~24_매출_건수', '남성_매출_건수', '여성_매출_건수',
       '연령대_10_매출_건수', '연령대_20_매출_건수', '연령대_30_매출_건수', '연령대_40_매출_건수',
       '연령대_50_매출_건수', '연령대_60_이상_매출_건수', '점포수'],
      dtype='object')
▶▶▶▶2017 매출 컬럼
 Index(['기준_년_코드', '기준_분기_코드', '상권_구분_코드', '상권_구분_코드_명', '상권_코드', '상권_코드_명',
       '서비스_업종_코드', '서비스_업종_코드_명', '분기당_매출_금액', '분기당_매출_건수', '주중_매출_비율',
       '주말_매출_비율', '월요일_매출_비율', '화요일_매출_비율', '수요일_매출_비율', '목요일_매출_비율',
       '금요일_매출_비율', '토요일_매출_비율', '일요일_매출_비율', '시간대_00~06_매출_비율',
       '시간대_06~11_매출_비율', '시간대_11~14_매출_비율', '시간대_14~17_매출_비율',
       '시간대_17~21_매출_비율', '시간대_21~24_매출_비율', '남성_매출_비율', '여성_매출_비율',
       '연령대_10_매출_비율', '연령대_20_매출_비율', '연령대_30_매출_비율', '연령대_40_매출_비율',
       '연령대_50_매출_비율', '연령대_60_이상_매출_비율', '주중_매출_금액', '주말_매출_금액', '월요일_매출_금액',
       '화요일_매출_금액', '수요일_매출_금액', '목요일_매출_금액', '금요일_매출_금액', '토요일_매출_금액',
       '일요일_매출_금액', '시간대_00~06_매출_금액', '시간대_06~11_매출_금액', '시간대_11~14_매출_금액',
       '시간대_14~17_매출_금액', '시간대_17~21_매출_금액', '시간대_21~24_매출_금액', '남성_매출_금액',
       '여성_매출_금액', '연령대_10_매출_금액', '연령대_20_매출_금액', '연령대_30_매출_금액',
       '연령대_40_매출_금액', '연령대_50_매출_금액', '연령대_60_이상_매출_금액', '주중_매출_건수',
       '주말_매출_건수', '월요일_매출_건수', '화요일_매출_건수', '수요일_매출_건수', '목요일_매출_건수',
       '금요일_매출_건수', '토요일_매출_건수', '일요일_매출_건수', '시간대_건수~06_매출_건수',
       '시간대_건수~11_매출_건수', '시간대_건수~14_매출_건수', '시간대_건수~17_매출_건수',
       '시간대_건수~21_매출_건수', '시간대_건수~24_매출_건수', '남성_매출_건수', '여성_매출_건수',
       '연령대_10_매출_건수', '연령대_20_매출_건수', '연령대_30_매출_건수', '연령대_40_매출_건수',
       '연령대_50_매출_건수', '연령대_60_이상_매출_건수', '점포수'],
      dtype='object')

In [ ]:
### 매출 데이터 6개년 합치기 --> 열은 모두 똑같길래 concat 사용
dfs = [sales_2022, sales_2021, sales_2020, sales_2019, sales_2018, sales_2017]
sales_6years = pd.concat(dfs, ignore_index=True)
sales_6years

,기준_년_코드,기준_분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,분기당_매출_금액,분기당_매출_건수,주중_매출_비율,주말_매출_비율,월요일_매출_비율,화요일_매출_비율,수요일_매출_비율,목요일_매출_비율,금요일_매출_비율,토요일_매출_비율,일요일_매출_비율,시간대_00~06_매출_비율,시간대_06~11_매출_비율,시간대_11~14_매출_비율,시간대_14~17_매출_비율,시간대_17~21_매출_비율,시간대_21~24_매출_비율,남성_매출_비율,여성_매출_비율,연령대_10_매출_비율,연령대_20_매출_비율,연령대_30_매출_비율,연령대_40_매출_비율,연령대_50_매출_비율,연령대_60_이상_매출_비율,주중_매출_금액,주말_매출_금액,월요일_매출_금액,화요일_매출_금액,수요일_매출_금액,목요일_매출_금액,금요일_매출_금액,토요일_매출_금액,일요일_매출_금액,시간대_00~06_매출_금액,시간대_06~11_매출_금액,시간대_11~14_매출_금액,시간대_14~17_매출_금액,시간대_17~21_매출_금액,시간대_21~24_매출_금액,남성_매출_금액,여성_매출_금액,연령대_10_매출_금액,연령대_20_매출_금액,연령대_30_매출_금액,연령대_40_매출_금액,연령대_50_매출_금액,연령대_60_이상_매출_금액,주중_매출_건수,주말_매출_건수,월요일_매출_건수,화요일_매출_건수,수요일_매출_건수,목요일_매출_건수,금요일_매출_건수,토요일_매출_건수,일요일_매출_건수,시간대_건수~06_매출_건수,시간대_건수~11_매출_건수,시간대_건수~14_매출_건수,시간대_건수~17_매출_건수,시간대_건수~21_매출_건수,시간대_건수~24_매출_건수,남성_매출_건수,여성_매출_건수,연령대_10_매출_건수,연령대_20_매출_건수,연령대_30_매출_건수,연령대_40_매출_건수,연령대_50_매출_건수,연령대_60_이상_매출_건수,점포수
0,2022,4,D,발달상권,2120139,대림3동사거리,CS300031,가구,205619535,220,100,0,5,94,0,0,1,0,0,0,0,95,5,0,0,6,94,0,0,0,0,5,95,205619535,0,10618849,193069986,0,0,1930700,0,0,0,0,195000686,10618849,0,0,12549549,193069986,0,0,0,0,10618849,195000686,220,0,44,44,88,0,44,0,0,0,0,176,44,0,0,176,44,0,0,0,0,44,176,*
1,2022,4,D,발달상권,2120068,사가정역,CS100005,제과점,1111094837,97349,68,32,13,14,14,11,17,18,14,0,16,21,21,33,9,39,61,1,15,23,22,23,15,759670537,351424300,139928134,154259080,150042322,125901713,189539288,200490775,150933525,0,180032749,233664326,232465867,365011878,99920017,405775472,623495718,13910395,158605425,234437046,229083786,239299473,153935066,68540,28809,12292,14348,13606,13479,14815,15930,12879,0,17576,18103,20355,32040,9275,33721,62371,1769,17108,23129,20604,18990,14492,5
2,2022,4,R,전통시장,2130322,고분다리전통시장,CS300018,의약품,168879417,10969,100,0,22,16,23,15,24,0,0,0,17,24,37,22,0,41,59,1,3,6,10,26,54,168879417,0,36849847,27096122,38978163,24910117,41045168,0,0,0,28627620,39930175,63185396,37136226,0,69665344,99214073,932500,5323335,10178372,17081115,43429247,91934848,10969,0,2095,1940,2149,2250,2535,0,0,0,1397,2974,3596,3002,0,4939,6030,78,312,1223,1169,2496,5691,3
3,2022,4,D,발달상권,2120230,송파사거리(송파역),CS300017,시계및귀금속,47289011,156,100,0,35,24,2,26,13,0,0,0,2,0,51,47,0,17,84,0,0,0,0,29,70,47289011,0,16751510,11222030,1111826,12273907,5929738,0,0,0,1037704,0,24237806,22013501,0,7782781,39506230,0,0,177892,0,13904585,33206534,156,0,30,59,29,23,15,0,0,0,15,0,59,82,0,59,97,0,0,15,0,38,103,5
4,2022,4,D,발달상권,2120234,가락시장역,CS200016,당구장,191548486,7142,61,39,12,11,12,11,16,26,13,22,5,5,13,28,28,92,8,2,15,29,16,19,20,117007334,74541152,23304794,20073154,23556976,20255901,29816509,48860126,25681026,41464197,9288902,9992852,23887746,52907612,54007177,171020276,15692619,2859273,27258860,53636797,30523164,35662104,36772697,4663,2479,872,799,933,856,1203,1663,816,1156,482,485,1070,2223,1726,6518,495,136,812,1417,1156,1815,1678,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
928233,2017,4,U,관광특구,1001496,강남 마이스 관광특구,CS300031,가구,330320365,2903,92,8,3,16,28,22,22,8,0,0,18,22,40,20,0,50,50,0,3,11,16,36,34,303278487,27041878,10541749,51425402,93271563,74018358,74021415,27041878,0,0,58936016,73945024,132514372,64924953,0,114857625,116434465,0,7058389,26105505,36196555,82390081,79541559,2688,215,154,429,701,672,732,215,0,0,429,701,1222,551,0,934,1083,0,122,248,371,652,625,9
928234,2017,4,U,관광특구,1001496,강남 마이스 관광특구,CS300032,가전제품,2174589379,9827,74,26,12,12,11,17,22,18,9,0,4,26,34,35,2,55,45,1,16,26,25,18,14,1601331971,573257408,267437873,264583513,235121431,363365708,470823446,385928170,187329238,0,81660524,561707758,728518241,753740715,48962141,966992622,787018046,21689710,286666400,447609815,443923933,309559978,244560837,6955,2872,1456,1292,1289,1202,1716,1482,1390,0,225,2583,2967,3698,354,4356,4513,228,2634,2525,1726,1251,511,9
928235,2017,4,U,관광특구,1001496,강남 마이스 관광특구,CS300035,인테리어,2839146155,103084,66,34,8,11,17,12,18,16,19,0,4,29,30,34,5,26,74,0,8,53,24,9,5,1871616983,967529172,221901716,317574736,486634087,326037632,519468812,438757563,528771609,0,100158055,818744224,841826972,950160404,128256500,695743479,2021268896,0,222206318,1452178320,638198436,256500074,147929227,67590,35494,10161,12266,12627,15524,17012,17752,17742,0,2647,28539,27411,39313,5174,25408,77434,0,12292,49939,23469,10804,6338,4
928236,2017,4,U,관광특구,1001496,강남 마이스 관광특구,CS300041,예술품,674145284,9152,81,19,13,18,16,14,20,11,8,0,5,31,24,32,8,50,50,0,8,36,25,16,15,544184202,129961082,88133105,123381400,105546999,92115544,135007154,74355351,55605731,0,31612155,210772436,164145743,214037542,53577408,155488268,153880451,0,24414081,111458818,78560410,48580808,46354600,6330,2822,1187,1088,1631,1286,1138,1337,1485,0,148,2574,2968,3017,445,2819,3413,0,791,2474,1137,940,890,9
928237,2017,4,U,관광특구,1001496,강남 마이스 관광특구,CS300043,전자상거래업,25637222,2530,71,30,6,6,8,26,26,11,19,4,16,30,25,17,7,39,61,0,9,56,28,5,2,18076747,7560475,1510867,1421273,1940143,6576420,6628044,2822007,4738468,1081725,4215353,7769981,6406615,4461279,1702269,9912656,15259305,111728,2326100,14144488,6917920,1216731,454996,1747,783,207,211,356,515,458,512,271,44,235,735,766,624,126,1365,1083,17,215,888,767,335,228,8

In [ ]:
# 데이터 확인용 --> ex. '상권_코드'가 1001496일 경우 뭐가 나오나
check_test = sales_6years[sales_6years['상권_코드'] == 1001496]

check_test.head(30)

,기준_년_코드,기준_분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,분기당_매출_금액,분기당_매출_건수,주중_매출_비율,주말_매출_비율,월요일_매출_비율,화요일_매출_비율,수요일_매출_비율,목요일_매출_비율,금요일_매출_비율,토요일_매출_비율,일요일_매출_비율,시간대_00~06_매출_비율,시간대_06~11_매출_비율,시간대_11~14_매출_비율,시간대_14~17_매출_비율,시간대_17~21_매출_비율,시간대_21~24_매출_비율,남성_매출_비율,여성_매출_비율,연령대_10_매출_비율,연령대_20_매출_비율,연령대_30_매출_비율,연령대_40_매출_비율,연령대_50_매출_비율,연령대_60_이상_매출_비율,주중_매출_금액,주말_매출_금액,월요일_매출_금액,화요일_매출_금액,수요일_매출_금액,목요일_매출_금액,금요일_매출_금액,토요일_매출_금액,일요일_매출_금액,시간대_00~06_매출_금액,시간대_06~11_매출_금액,시간대_11~14_매출_금액,시간대_14~17_매출_금액,시간대_17~21_매출_금액,시간대_21~24_매출_금액,남성_매출_금액,여성_매출_금액,연령대_10_매출_금액,연령대_20_매출_금액,연령대_30_매출_금액,연령대_40_매출_금액,연령대_50_매출_금액,연령대_60_이상_매출_금액,주중_매출_건수,주말_매출_건수,월요일_매출_건수,화요일_매출_건수,수요일_매출_건수,목요일_매출_건수,금요일_매출_건수,토요일_매출_건수,일요일_매출_건수,시간대_건수~06_매출_건수,시간대_건수~11_매출_건수,시간대_건수~14_매출_건수,시간대_건수~17_매출_건수,시간대_건수~21_매출_건수,시간대_건수~24_매출_건수,남성_매출_건수,여성_매출_건수,연령대_10_매출_건수,연령대_20_매출_건수,연령대_30_매출_건수,연령대_40_매출_건수,연령대_50_매출_건수,연령대_60_이상_매출_건수,점포수
3308,2022,4,U,관광특구,1001496,강남 마이스 관광특구,CS200028,미용실,769636911,10247,62,39,10,13,11,12,16,25,13,0,2,25,33,34,7,41,59,0,8,18,35,26,13,473115285,296521626,79185023,99488153,84715988,88517757,121208364,193052339,103469287,0,15194033,189493021,251570233,262870316,50509308,303443932,439566536,2363659,59268227,136981260,262241393,189109331,93046600,7262,2985,1300,1357,1433,1333,1839,1672,1313,0,482,2571,3176,3438,580,5861,4292,73,991,2859,3115,2106,1010,6
3310,2022,4,U,관광특구,1001496,강남 마이스 관광특구,CS100003,일식음식점,4282966621,111768,69,31,12,12,15,15,16,17,14,0,0,39,18,40,3,47,53,1,26,33,20,13,8,2969231144,1313735477,491659443,515256915,619563569,654188944,688562273,714256225,599479252,0,5501886,1676316444,772409372,1709570926,119167993,1522779964,1699333222,45969012,847981540,1057712488,627441199,401397727,241611220,80144,31624,13712,13970,16274,17917,18271,17174,14450,0,251,47676,20283,41903,1655,38409,54115,1798,26358,31178,16625,10488,6079,21
3979,2022,4,U,관광특구,1001496,강남 마이스 관광특구,CS300022,화장품,4231569244,44827,69,32,13,12,16,13,16,17,15,0,6,23,34,34,3,30,70,1,18,35,24,13,9,2899400947,1332168297,528385091,490582519,654435512,567636448,658361377,696905107,635263190,0,254593904,958736186,1427532776,1450174413,140531965,1210787378,2809873563,35448860,741078343,1420911055,956324608,525946945,340951129,32681,12146,5235,5818,7603,7124,6901,6286,5860,0,3480,9650,14517,15670,1510,11480,32594,462,10544,15496,9597,5063,2911,54
3981,2022,4,U,관광특구,1001496,강남 마이스 관광특구,CS300018,의약품,3797624579,277796,81,19,16,23,13,14,16,12,7,0,15,31,34,21,0,54,46,0,16,24,19,25,16,3074186682,723437897,599698216,863648976,480872498,542186686,587780306,456436846,267001051,0,562696022,1163846930,1283871070,784039662,3170895,1815875510,1567843716,10862962,539515121,800349793,636157244,855530992,541303111,213788,64008,43816,42287,40711,41829,45145,37044,26964,0,39871,88970,84817,63819,319,123446,143461,1701,60564,82693,54667,40326,26956,10
3983,2022,4,U,관광특구,1001496,강남 마이스 관광특구,CS300002,편의점,2412105658,420704,80,20,18,14,16,16,16,11,9,2,21,21,19,27,9,60,40,1,25,32,25,13,4,1929611472,482494186,434030530,343431870,377306007,387511152,387331913,267636468,214857718,52070902,510014760,514933439,461983388,646237030,226866139,1172451186,779216628,17350552,490220885,618069391,480472248,260344098,85210640,331485,89219,59318,65666,68501,70803,67197,49824,39395,5876,113267,97781,86974,89732,27074,220819,172320,5198,108178,131039,88484,45233,15007,11
12092,2022,4,U,관광특구,1001496,강남 마이스 관광특구,CS300043,전자상거래업,4770649,1016,55,45,18,4,11,6,17,18,26,0,0,29,38,34,0,3,97,7,76,10,2,4,0,2642805,2127844,855025,174892,505242,291486,816160,874456,1253388,0,0,1360267,1797495,1612887,0,140885,4629764,349783,3619281,485809,102020,194324,19432,577,439,189,43,116,64,165,190,249,0,0,267,394,355,0,34,982,77,779,87,24,44,5,6
12094,2022,4,U,관광특구,1001496,강남 마이스 관광특구,CS300031,가구,8512320761,3912,64,36,10,19,12,11,13,19,17,0,9,33,42,16,0,42,59,0,3,7,19,27,45,5431244041,3081076720,820854469,1595890527,1019635887,904032509,1090830649,1636422198,1444654522,0,751421953,2771309012,3606261455,1383328341,0,3536563097,4975757664,0,218106902,608029596,1587091186,2302581151,3796511926,2644,1268,563,529,635,458,459,634,634,0,282,1092,1974,564,0,1421,2491,0,106,212,781,785,2028,6
12096,2022,4,U,관광특구,1001496,강남 마이스 관광특구,CS300021,문구,1922740948,138384,73,28,12,14,15,15,17,16,12,0,10,26,31,31,2,32,68,2,34,27,21,11,5,1393657425,529083523,229175053,264295095,286274744,293492766,320419767,301501396,227582127,0,187323213,505758004,595432274,592911227,41316230,432955337,904365553,23813234,456434300,365391392,275761426,146459471,69461065,95549,42835,15046,17097,19510,20842,23054,24870,17965,0,11262,34676,43618,45694,3134,37811,83625,2754,46262,34730,19596,12373,5721,10
20364,2022,4,U,관광특구,1001496,강남 마이스 관광특구,CS200024,스포츠클럽,1136014176,2814,96,4,21,23,27,9,16,3,1,0,8,26,19,38,10,61,39,0,10,22,31,25,12,1092667190,43346986,234033491,264443418,310966701,101466128,181757452,32697037,10649949,0,89466434,293232843,213220447,429625735,110468717,561351338,357145221,0,93709415,202526544,285809152,226745976,109705470,2510,304,498,659,609,423,321,211,93,0,397,514,541,914,448,1488,820,0,101,540,955,584,127,*
20366,2022,4,U,관광특구,1001496,강남 마이스 관광특구,CS100010,커피-음료,4085317793,475251,72,29,12,13,14,16,16,16,13,0,15,35,28,21,2,38,62,1,26,36,20,12,5,2920052453,1165265340,495354714,538024641,589791949,643075720,653805429,631667550,533597790,579620,621382005,1421519885,1133741089,848812117,59283077,1276719394,2075179079,46524249,866438709,1198270733,664452237,408094810,168117733,336625,138626,57274,63995,67896,72528,74932,73764,64862,129,91562,159938,123523,93922,6177,154791,273753,6643,116086,154325,81522,51708,18259,52
20368,2022,4,U,관광특구,1001496,강남 마이스 관광특구,CS100008,분식전문점,13829363887,313683,62,38,7,8,15,17,16,21,17,0,1,26,22,41,11,48,52,1,24,37,22,12,5,8557116053,5272247834,948371890,1069228271,2028391117,2300950478,2210174297,2902906269,2369341565,0,85122069,3628505996,2975699504,5683538936,1456497382,5378149072,5753134642,120350230,2635650032,4100572586,2388089199,1323788650,562833016,234737,78946,39559,45059,49257,50868,49994,42789,36157,0,8065,135487,62681,101168,6282,105131,158597,4268,70336,88489,52854,33738,14042,30
20370,2022,4,U,관광특구,1001496,강남 마이스 관광특구,CS300032,가전제품,1364810577,4605,69,31,14,16,9,10,21,17,14,0,3,22,32,38,5,59,41,2,20,34,23,20,2,947592304,417218273,187424899,214424871,118269605,142346794,285126135,229027683,188190590,0,38599686,304742913,437590420,512327168,71550390,632133858,442845092,17927950,210644557,361034167,250851077,213049256,21471942,3061,1544,630,564,504,636,727,818,726,0,132,1128,1452,1761,132,2208,1920,90,1044,1278,894,666,156,8
23309,2022,4,U,관광특구,1001496,강남 마이스 관광특구,CS200006,일반의원,1853555425,16024,90,10,18,21,12,22,18,10,0,0,21,40,27,12,0,46,54,0,11,21,24,28,16,1673990342,179565083,338563553,384183373,218936851,408453398,323853167,179565083,0,0,397562775,736592832,497065533,222334285,0,846519043,1007036382,549155,196421016,392339028,435631306,525426789,303188131,14672,1352,3046,2998,3065,2648,2915,1352,0,0,3551,5858,4715,1900,0,7697,8327,40,2468,4781,3685,3077,1973,5
23311,2022,4,U,관광특구,1001496,강남 마이스 관광특구,CS100006,패스트푸드점,1842714083,152432,69,31,12,12,14,15,16,17,14,0,6,33,20,35,5,51,49,2,30,35,19,9,5,1263897841,578816242,219527910,228174586,262453898,266998927,286742520,320857665,257958577,0,113634722,616192505,376811437,648312003,87763416,798828597,759783488,27421322,469607064,543766061,300326060,142008152,75483425,109442,42990,18807,20619,22697,22983,24336,23520,19470,0,19445,47707,33101,45635,6544,71500,68913,2992,43927,46903,26325,13203,7060,14
23313,2022,4,U,관광특구,1001496,강남 마이스 관광특구,CS300015,가방,9625249911,376291,61,39,13,13,10,11,14,20,19,0,1,24,32,39,4,32,68,1,18,27,21,19,15,5874178289,3751071622,1211083901,1224252312,992274566,1082643817,1363923693,1957792129,1793279493,0,83142604,2259478193,3105058643,3754861649,422708822,3063713002,6561536909,52598425,1750096101,2602114168,1982610590,1776925255,1460905372,237140,139151,45381,45564,44780,45764,55651,72256,66895,0,4318,89774,117412,146420,18367,108318,267973,6265,88932,106269,75555,57610,41660,23
23315,2022,4,U,관광특구,1001496,강남 마이스 관광특구,CS300004,핸드폰,824320089,9948,89,11,8,32,37,8,3,9,2,0,1,26,36,38,0,21,79,0,44,22,16,12,6,734739683,89580406,68545193,265885917,304065177,69196990,27046406,76100455,13479951,0,4216990,212654671,295239774,311487801,720853,139744568,514278175,720853,289710832,142678440,102000704,79834473,39077443,7136,2812,1586,1009,1442,1729,1370,1514,1298,0,216,3317,3099,3244,72,3460,5262,72,1731,2163,2306,1658,792,8
23317,2022,4,U,관광특구,1001496,강남 마이스 관광특구,CS300003,컴퓨터및주변장치판매,408854268,4212,96,4,3,2,63,27,0,4,0,0,17,33,48,3,0,72,28,0,28,8,48,17,0,391560622,17293646,13896678,7720378,258307357,111636209,0,17293646,0,0,68377178,133253266,194562406,12661418,0,46746772,18528906,0,18528906,4941041,30997202,10808528,0,2669,1543,927,926,562,254,0,1543,0,0,63,1797,808,1544,0,1606,1853,0,1544,617,681,618,0,21
23319,2022,4,U,관광특구,1001496,강남 마이스 관광특구,CS300017,시계및귀금속,1463361463,1487,74,26,25,33,0,0,16,20,7,0,0,7,62,31,0,13,87,0,0,44,0,26,30,1078494961,384866502,365335564,476501383,0,0,236658014,288683320,96183182,0,0,106095030,901633724,455632709,0,115847894,760381461,0,0,387541973,0,224885942,263801440,818,669,268,267,0,0,283,401,268,0,0,282,669,536,0,268,951,0,0,669,0,149,402,25
23321,2022,4,U,관광특구,1001496,강남 마이스 관광특구,CS300026,완구,383996294,3093,45,56,5,2,13,16,10,43,13,0,2,11,43,44,0,63,37,8,26,25,38,3,0,170903329,213092965,18812417,7640150,48388566,59348053,36714143,163779524,49313441,0,7353609,40989564,166778274,168874847,0,231508577,135198791,28931826,96897858,91552241,138257046,11068398,0,1504,1589,227,113,341,369,454,1021,568,0,113,511,1193,1276,0,1687,1349,228,857,687,1063,200,0,6
23323,2022,4,U,관광특구,1001496,강남 마이스 관광특구,CS100005,제과점,3275467837,268493,65,35,12,11,13,14,16,19,16,0,6,29,26,34,4,44,56,2,26,31,23,12,5,2143589485,1131878352,387588378,365445972,431185921,441714981,517654233,605549798,526328554,815950,201124861,962982969,862126042,1117475478,130942537,1257508618,1574727122,67489781,739791567,876824293,647022128,350255694,150852276,179715,88778,32365,32230,35837,37658,41625,47437,41341,172,26846,70453,69820,89284,11918,101873,145541,6831,69501,75761,53747,29364,12209,16
23325,2022,4,U,관광특구,1001496,강남 마이스 관광특구,CS100002,중식음식점,8631791558,164049,66,34,12,12,13,14,16,19,15,0,0,35,21,41,2,43,57,1,24,32,22,14,8,5704695316,2927096242,1028211485,1042502229,1117026749,1160979358,1355975495,1601564617,1325531625,0,6545754,2999734743,1840944418,3574549788,210016855,2998485622,3955518876,57079332,1668867636,2216607965,1495309983,948277612,567861969,110128,53921,21399,20445,21318,21918,25048,29084,24837,0,208,54813,38131,68259,2638,56150,84820,1571,37044,45148,28570,18675,9960,11
23327,2022,4,U,관광특구,1001496,강남 마이스 관광특구,CS300016,안경,735377629,4259,71,29,16,16,16,7,16,15,14,0,7,26,31,37,0,51,49,0,9,34,20,28,8,525368540,210009089,120223626,119596627,118981292,52586925,113980070,111062697,98946392,0,50849575,187502764,225841044,269858503,1325743,365911215,354261228,304104,66750419,244652958,146074135,203747486,58643343,3281,978,632,628,789,573,659,491,487,0,325,1353,1225,1302,54,1554,2659,5,755,1365,1028,708,350,9
23329,2022,4,U,관광특구,1001496,강남 마이스 관광특구,CS300014,신발,423249715,1259,58,42,12,9,13,6,18,28,14,0,0,22,35,41,2,58,42,3,25,32,25,13,2,244323610,178926105,51758421,38453835,55529646,24631981,73949727,117811218,61114887,0,1658599,94079536,146961181,172472188,8078211,243600978,179648737,14273066,104286218,137180262,104290830,56281545,6937794,701,558,126,108,144,102,221,354,204,0,12,256,424,519,48,781,478,24,338,466,284,111,36,43
23331,2022,4,U,관광특구,1001496,강남 마이스 관광특구,CS300001,슈퍼마켓,336318734,18519,56,44,9,10,9,11,17,24,20,0,2,23,31,33,10,40,60,2,38,27,26,6,2,189510901,146807833,29806996,33366333,31310806,37682685,57344081,81163554,65644279,183432,8076159,78838669,103750052,111483938,33986484,128679360,191149153,5545015,121278306,85103461,82598799,18049974,7252958,11256,7263,2095,2198,2027,2130,2806,4355,2908,23,999,4407,4805,5604,2681,9572,8822,247,4896,5419,6493,1201,138,14
23333,2022,4,U,관광특구,1001496,강남 마이스 관광특구,CS200030,피부관리실,82341742,448,72,28,12,16,18,14,12,13,15,0,4,22,33,39,2,89,11,0,4,24,31,14,27,59305093,23036649,9995241,13231795,14850071,11327939,9900047,11042361,11994288,0,3236554,17991432,27129938,32365541,1618277,29414565,3617325,0,1142313,7996192,10376011,4569253,8948119,325,123,39,66,86,67,67,67,56,0,10,114,124,190,10,191,39,0,10,67,68,19,67,*
23335,2022,4,U,관광특구,1001496,강남 마이스 관광특구,CS300024,운동/경기용품,1475707139,1695,67,33,4,9,11,31,13,29,4,0,17,49,31,3,0,72,28,0,0,0,18,35,47,995204826,480502313,55880739,128544774,159409506,458128827,193240980,426465193,54037120,0,253868510,720590299,461197288,40051042,0,714398281,280865880,0,0,3390564,180547555,344561871,466764170,1547,148,255,444,297,360,191,106,42,0,360,742,530,63,0,1229,276,0,0,21,106,360,1018,12
28822,2022,4,U,관광특구,1001496,강남 마이스 관광특구,CS200007,치과의원,583670779,3903,89,11,14,13,20,12,30,11,0,0,8,42,33,17,0,59,41,0,4,15,26,30,25,517711285,65959494,83723548,75411261,116446930,67955470,174174076,65959494,0,0,48240762,242012739,191987407,101429871,0,344094058,239576721,0,22396800,87337625,153010720,175813275,145112359,3354,549,648,684,772,495,755,549,0,0,477,1510,1430,486,0,2298,1605,0,253,631,893,1045,1081,3
28823,2022,4,U,관광특구,1001496,강남 마이스 관광특구,CS300028,화초,658389405,9080,79,21,10,8,7,31,23,15,6,0,10,42,24,25,0,58,42,0,17,32,23,7,21,520948650,137440755,67405293,54052332,44889332,204470305,150131388,99211928,38228827,0,63555022,275635180,154764053,163348046,1087104,239390163,173851124,522949,68223297,133492513,94375304,29977053,86650171,5903,3177,1091,805,749,1197,2061,1985,1192,0,1152,2491,2307,3094,36,4594,3400,54,2085,2412,1687,571,1183,5
28824,2022,4,U,관광특구,1001496,강남 마이스 관광특구,CS200029,네일숍,79868475,688,70,31,11,14,10,13,21,19,12,0,0,17,12,71,0,21,79,1,3,22,21,29,25,55503718,24364757,8971024,10944170,8084306,10568713,16935505,15106150,9258607,0,0,13508461,9434354,56925660,0,15389942,56490088,511260,2134912,15455257,15221603,20950065,17606933,528,160,88,112,120,80,128,96,64,0,0,224,136,328,0,105,567,8,48,284,139,113,80,3
33020,2022,4,U,관광특구,1001496,강남 마이스 관광특구,CS100004,양식음식점,3259990012,79490,66,34,11,12,13,14,16,18,16,0,1,35,19,39,6,43,57,1,24,34,25,11,5,2153278843,1106711169,357351328,379009958,430472397,460056198,526388962,589276333,517434836,0,21111512,1144825037,631527550,1273604908,188921005,1114220878,1463366693,28181177,607074829,878335673,647691801,291874297,124429791,55963,23527,9763,10735,11410,11993,12062,12540,10987,0,2821,30929,16403,26850,2487,26384,41489,833,17194,24515,15467,6941,2921,36

In [ ]:
### 상권코드에 맞춰 자치구, 행정동 끌어오기

# '자치구', '행정동' 열 생성
sales_6years['자치구'] = ''
sales_6years['행정동'] = ''

# 자치구, 행정동 채우기
for index, row in sales_6years.iterrows():
    mask = seoul_gudong['상권_코드'] == row['상권_코드']
    matching_data = seoul_gudong[mask]
    if not matching_data.empty:
        sales_6years.at[index, '자치구'] = matching_data['자치구'].values[0]
        sales_6years.at[index, '행정동'] = matching_data['행정동'].values[0]

sales_6years

,기준_년_코드,기준_분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,분기당_매출_금액,분기당_매출_건수,주중_매출_비율,주말_매출_비율,월요일_매출_비율,화요일_매출_비율,수요일_매출_비율,목요일_매출_비율,금요일_매출_비율,토요일_매출_비율,일요일_매출_비율,시간대_00~06_매출_비율,시간대_06~11_매출_비율,시간대_11~14_매출_비율,시간대_14~17_매출_비율,시간대_17~21_매출_비율,시간대_21~24_매출_비율,남성_매출_비율,여성_매출_비율,연령대_10_매출_비율,연령대_20_매출_비율,연령대_30_매출_비율,연령대_40_매출_비율,연령대_50_매출_비율,연령대_60_이상_매출_비율,주중_매출_금액,주말_매출_금액,월요일_매출_금액,화요일_매출_금액,수요일_매출_금액,목요일_매출_금액,금요일_매출_금액,토요일_매출_금액,일요일_매출_금액,시간대_00~06_매출_금액,시간대_06~11_매출_금액,시간대_11~14_매출_금액,시간대_14~17_매출_금액,시간대_17~21_매출_금액,시간대_21~24_매출_금액,남성_매출_금액,여성_매출_금액,연령대_10_매출_금액,연령대_20_매출_금액,연령대_30_매출_금액,연령대_40_매출_금액,연령대_50_매출_금액,연령대_60_이상_매출_금액,주중_매출_건수,주말_매출_건수,월요일_매출_건수,화요일_매출_건수,수요일_매출_건수,목요일_매출_건수,금요일_매출_건수,토요일_매출_건수,일요일_매출_건수,시간대_건수~06_매출_건수,시간대_건수~11_매출_건수,시간대_건수~14_매출_건수,시간대_건수~17_매출_건수,시간대_건수~21_매출_건수,시간대_건수~24_매출_건수,남성_매출_건수,여성_매출_건수,연령대_10_매출_건수,연령대_20_매출_건수,연령대_30_매출_건수,연령대_40_매출_건수,연령대_50_매출_건수,연령대_60_이상_매출_건수,점포수,자치구,행정동
0,2022,4,D,발달상권,2120139,대림3동사거리,CS300031,가구,205619535,220,100,0,5,94,0,0,1,0,0,0,0,95,5,0,0,6,94,0,0,0,0,5,95,205619535,0,10618849,193069986,0,0,1930700,0,0,0,0,195000686,10618849,0,0,12549549,193069986,0,0,0,0,10618849,195000686,220,0,44,44,88,0,44,0,0,0,0,176,44,0,0,176,44,0,0,0,0,44,176,*,영등포구,대림3동
1,2022,4,D,발달상권,2120068,사가정역,CS100005,제과점,1111094837,97349,68,32,13,14,14,11,17,18,14,0,16,21,21,33,9,39,61,1,15,23,22,23,15,759670537,351424300,139928134,154259080,150042322,125901713,189539288,200490775,150933525,0,180032749,233664326,232465867,365011878,99920017,405775472,623495718,13910395,158605425,234437046,229083786,239299473,153935066,68540,28809,12292,14348,13606,13479,14815,15930,12879,0,17576,18103,20355,32040,9275,33721,62371,1769,17108,23129,20604,18990,14492,5,중랑구,면목3.8동
2,2022,4,R,전통시장,2130322,고분다리전통시장,CS300018,의약품,168879417,10969,100,0,22,16,23,15,24,0,0,0,17,24,37,22,0,41,59,1,3,6,10,26,54,168879417,0,36849847,27096122,38978163,24910117,41045168,0,0,0,28627620,39930175,63185396,37136226,0,69665344,99214073,932500,5323335,10178372,17081115,43429247,91934848,10969,0,2095,1940,2149,2250,2535,0,0,0,1397,2974,3596,3002,0,4939,6030,78,312,1223,1169,2496,5691,3,강동구,천호3동
3,2022,4,D,발달상권,2120230,송파사거리(송파역),CS300017,시계및귀금속,47289011,156,100,0,35,24,2,26,13,0,0,0,2,0,51,47,0,17,84,0,0,0,0,29,70,47289011,0,16751510,11222030,1111826,12273907,5929738,0,0,0,1037704,0,24237806,22013501,0,7782781,39506230,0,0,177892,0,13904585,33206534,156,0,30,59,29,23,15,0,0,0,15,0,59,82,0,59,97,0,0,15,0,38,103,5,송파구,석촌동
4,2022,4,D,발달상권,2120234,가락시장역,CS200016,당구장,191548486,7142,61,39,12,11,12,11,16,26,13,22,5,5,13,28,28,92,8,2,15,29,16,19,20,117007334,74541152,23304794,20073154,23556976,20255901,29816509,48860126,25681026,41464197,9288902,9992852,23887746,52907612,54007177,171020276,15692619,2859273,27258860,53636797,30523164,35662104,36772697,4663,2479,872,799,933,856,1203,1663,816,1156,482,485,1070,2223,1726,6518,495,136,812,1417,1156,1815,1678,12,송파구,가락본동
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
928233,2017,4,U,관광특구,1001496,강남 마이스 관광특구,CS300031,가구,330320365,2903,92,8,3,16,28,22,22,8,0,0,18,22,40,20,0,50,50,0,3,11,16,36,34,303278487,27041878,10541749,51425402,93271563,74018358,74021415,27041878,0,0,58936016,73945024,132514372,64924953,0,114857625,116434465,0,7058389,26105505,36196555,82390081,79541559,2688,215,154,429,701,672,732,215,0,0,429,701,1222,551,0,934,1083,0,122,248,371,652,625,9,강남구,삼성1동
928234,2017,4,U,관광특구,1001496,강남 마이스 관광특구,CS300032,가전제품,2174589379,9827,74,26,12,12,11,17,22,18,9,0,4,26,34,35,2,55,45,1,16,26,25,18,14,1601331971,573257408,267437873,264583513,235121431,363365708,470823446,385928170,187329238,0,81660524,561707758,728518241,753740715,48962141,966992622,787018046,21689710,286666400,447609815,443923933,309559978,244560837,6955,2872,1456,1292,1289,1202,1716,1482,1390,0,225,2583,2967,3698,354,4356,4513,228,2634,2525,1726,1251,511,9,강남구,삼성1동
928235,2017,4,U,관광특구,1001496,강남 마이스 관광특구,CS300035,인테리어,2839146155,103084,66,34,8,11,17,12,18,16,19,0,4,29,30,34,5,26,74,0,8,53,24,9,5,1871616983,967529172,221901716,317574736,486634087,326037632,519468812,438757563,528771609,0,100158055,818744224,841826972,950160404,128256500,695743479,2021268896,0,222206318,1452178320,638198436,256500074,147929227,67590,35494,10161,12266,12627,15524,17012,17752,17742,0,2647,28539,27411,39313,5174,25408,77434,0,12292,49939,23469,10804,6338,4,강남구,삼성1동
928236,2017,4,U,관광특구,1001496,강남 마이스 관광특구,CS300041,예술품,674145284,9152,81,19,13,18,16,14,20,11,8,0,5,31,24,32,8,50,50,0,8,36,25,16,15,544184202,129961082,88133105,123381400,105546999,92115544,135007154,74355351,55605731,0,31612155,210772436,164145743,214037542,53577408,155488268,153880451,0,24414081,111458818,78560410,48580808,46354600,6330,2822,1187,1088,1631,1286,1138,1337,1485,0,148,2574,2968,3017,445,2819,3413,0,791,2474,1137,940,890,9,강남구,삼성1동
928237,2017,4,U,관광특구,1001496,강남 마이스 관광특구,CS300043,전자상거래업,25637222,2530,71,30,6,6,8,26,26,11,19,4,16,30,25,17,7,39,61,0,9,56,28,5,2,18076747,7560475,1510867,1421273,1940143,6576420,6628044,2822007,4738468,1081725,4215353,7769981,6406615,4461279,1702269,9912656,15259305,111728,2326100,14144488,6917920,1216731,454996,1747,783,207,211,356,515,458,512,271,44,235,735,766,624,126,1365,1083,17,215,888,767,335,228,8,강남구,삼성1동

### 매출+점포 병합

In [ ]:
# 두 데이터프레임 (sales, store)의 지정 컬럼의 값이 같을 때 점포데이터의 남은 컬럼 값 가져오기
df_merged = pd.merge(sales_6years, store_6years, on=['기준_년_코드', '기준_분기_코드', '상권_구분_코드', '상권_구분_코드_명', '상권_코드', '상권_코드_명', '서비스_업종_코드', '서비스_업종_코드_명'], how='inner')

In [ ]:
# 총 매출 금액 컬럼 생성
df_merged['총_매출_금액'] = df_merged['주중_매출_금액'] + df_merged['주말_매출_금액']
df_merged.columns

Index(['기준_년_코드', '기준_분기_코드', '상권_구분_코드', '상권_구분_코드_명', '상권_코드', '상권_코드_명',
       '서비스_업종_코드', '서비스_업종_코드_명', '분기당_매출_금액', '분기당_매출_건수', '주중_매출_비율',
       '주말_매출_비율', '월요일_매출_비율', '화요일_매출_비율', '수요일_매출_비율', '목요일_매출_비율',
       '금요일_매출_비율', '토요일_매출_비율', '일요일_매출_비율', '시간대_00~06_매출_비율',
       '시간대_06~11_매출_비율', '시간대_11~14_매출_비율', '시간대_14~17_매출_비율',
       '시간대_17~21_매출_비율', '시간대_21~24_매출_비율', '남성_매출_비율', '여성_매출_비율',
       '연령대_10_매출_비율', '연령대_20_매출_비율', '연령대_30_매출_비율', '연령대_40_매출_비율',
       '연령대_50_매출_비율', '연령대_60_이상_매출_비율', '주중_매출_금액', '주말_매출_금액', '월요일_매출_금액',
       '화요일_매출_금액', '수요일_매출_금액', '목요일_매출_금액', '금요일_매출_금액', '토요일_매출_금액',
       '일요일_매출_금액', '시간대_00~06_매출_금액', '시간대_06~11_매출_금액', '시간대_11~14_매출_금액',
       '시간대_14~17_매출_금액', '시간대_17~21_매출_금액', '시간대_21~24_매출_금액', '남성_매출_금액',
       '여성_매출_금액', '연령대_10_매출_금액', '연령대_20_매출_금액', '연령대_30_매출_금액',
       '연령대_40_매출_금액', '연령대_50_매출_금액', '연령대_60_이상_매출_금액', '주중_매출_건수',
       '주말_매출_건수', '월요일_매출_건수', '화요일_매출_건수', '수요일_매출_건수', '목요일_매출_건수',
       '금요일_매출_건수', '토요일_매출_건수', '일요일_매출_건수', '시간대_건수~06_매출_건수',
       '시간대_건수~11_매출_건수', '시간대_건수~14_매출_건수', '시간대_건수~17_매출_건수',
       '시간대_건수~21_매출_건수', '시간대_건수~24_매출_건수', '남성_매출_건수', '여성_매출_건수',
       '연령대_10_매출_건수', '연령대_20_매출_건수', '연령대_30_매출_건수', '연령대_40_매출_건수',
       '연령대_50_매출_건수', '연령대_60_이상_매출_건수', '점포수', '자치구', '행정동', '점포_수',
       '유사_업종_점포_수', '개업_율', '개업_점포_수', '폐업_률', '폐업_점포_수', '프랜차이즈_점포_수',
       '총_매출_금액'],
      dtype='object')

In [ ]:
# 필요한 컬럼만 추출
df_preprocessed = df_merged[['기준_년_코드', '기준_분기_코드', '자치구', '행정동', '상권_코드', '서비스_업종_코드', '서비스_업종_코드_명', '점포_수', '유사_업종_점포_수',
                             '개업_율', '개업_점포_수', '폐업_률', '폐업_점포_수', '프랜차이즈_점포_수',
                             '총_매출_금액', '분기당_매출_금액', '주중_매출_금액', '주말_매출_금액', '남성_매출_금액', '여성_매출_금액']]
df_preprocessed

,기준_년_코드,기준_분기_코드,자치구,행정동,상권_코드,서비스_업종_코드,서비스_업종_코드_명,점포_수,유사_업종_점포_수,개업_율,개업_점포_수,폐업_률,폐업_점포_수,프랜차이즈_점포_수,총_매출_금액,분기당_매출_금액,주중_매출_금액,주말_매출_금액,남성_매출_금액,여성_매출_금액
0,2022,4,영등포구,대림3동,2120139,CS300031,가구,2,2,0,0,0,0,0,205619535,205619535,205619535,0,12549549,193069986
1,2022,4,중랑구,면목3.8동,2120068,CS100005,제과점,3,5,20,1,0,0,2,1111094837,1111094837,759670537,351424300,405775472,623495718
2,2022,4,강동구,천호3동,2130322,CS300018,의약품,3,3,0,0,0,0,0,168879417,168879417,168879417,0,69665344,99214073
3,2022,4,송파구,석촌동,2120230,CS300017,시계및귀금속,4,5,0,0,0,0,1,47289011,47289011,47289011,0,7782781,39506230
4,2022,4,송파구,가락본동,2120234,CS200016,당구장,11,12,0,0,0,0,1,191548486,191548486,117007334,74541152,171020276,15692619
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
912344,2017,4,강남구,삼성1동,1001496,CS300031,가구,9,9,0,0,0,0,0,330320365,330320365,303278487,27041878,114857625,116434465
912345,2017,4,강남구,삼성1동,1001496,CS300032,가전제품,9,9,0,0,0,0,0,2174589379,2174589379,1601331971,573257408,966992622,787018046
912346,2017,4,강남구,삼성1동,1001496,CS300035,인테리어,4,4,0,0,0,0,0,2839146155,2839146155,1871616983,967529172,695743479,2021268896
912347,2017,4,강남구,삼성1동,1001496,CS300041,예술품,9,9,0,0,0,0,0,674145284,674145284,544184202,129961082,155488268,153880451
912348,2017,4,강남구,삼성1동,1001496,CS300043,전자상거래업,8,8,0,0,0,0,0,25637222,25637222,18076747,7560475,9912656,15259305

In [ ]:
df_preprocessed.자치구.nunique()

25

### 대분류, 중분류 붙이기

In [ ]:
### '서비스_업종_코드_명'(업종명)에 따라 대분류, 중분류 채우기

# '대분류', '중분류' 컬럼 생성
df_preprocessed['대분류'] = ''
df_preprocessed['중분류'] = ''

# 중분류, 대분류 채우기
for index, row in df_preprocessed.iterrows():
    mask = category['업종명'] == row['서비스_업종_코드_명']
    matching_data = category[mask]
    if not matching_data.empty:
        df_preprocessed.at[index, '대분류'] = matching_data['대분류'].values[0]
        df_preprocessed.at[index, '중분류'] = matching_data['중분류'].values[0]

# 결과 확인
df_preprocessed

<ipython-input-15-20e146ff1257>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_preprocessed['대분류'] = ''
<ipython-input-15-20e146ff1257>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_preprocessed['중분류'] = ''

,기준_년_코드,기준_분기_코드,자치구,행정동,상권_코드,서비스_업종_코드,서비스_업종_코드_명,점포_수,유사_업종_점포_수,개업_율,개업_점포_수,폐업_률,폐업_점포_수,프랜차이즈_점포_수,총_매출_금액,분기당_매출_금액,주중_매출_금액,주말_매출_금액,남성_매출_금액,여성_매출_금액,대분류,중분류
0,2022,4,영등포구,대림3동,2120139,CS300031,가구,2,2,0,0,0,0,0,205619535,205619535,205619535,0,12549549,193069986,소매,가구/인테리어
1,2022,4,중랑구,면목3.8동,2120068,CS100005,제과점,3,5,20,1,0,0,2,1111094837,1111094837,759670537,351424300,405775472,623495718,외식,카페/베이커리
2,2022,4,강동구,천호3동,2130322,CS300018,의약품,3,3,0,0,0,0,0,168879417,168879417,168879417,0,69665344,99214073,소매,의료
3,2022,4,송파구,석촌동,2120230,CS300017,시계및귀금속,4,5,0,0,0,0,1,47289011,47289011,47289011,0,7782781,39506230,소매,의류/잡화
4,2022,4,송파구,가락본동,2120234,CS200016,당구장,11,12,0,0,0,0,1,191548486,191548486,117007334,74541152,171020276,15692619,서비스,오락
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
912344,2017,4,강남구,삼성1동,1001496,CS300031,가구,9,9,0,0,0,0,0,330320365,330320365,303278487,27041878,114857625,116434465,소매,가구/인테리어
912345,2017,4,강남구,삼성1동,1001496,CS300032,가전제품,9,9,0,0,0,0,0,2174589379,2174589379,1601331971,573257408,966992622,787018046,소매,가구/인테리어
912346,2017,4,강남구,삼성1동,1001496,CS300035,인테리어,4,4,0,0,0,0,0,2839146155,2839146155,1871616983,967529172,695743479,2021268896,소매,가구/인테리어
912347,2017,4,강남구,삼성1동,1001496,CS300041,예술품,9,9,0,0,0,0,0,674145284,674145284,544184202,129961082,155488268,153880451,소매,가구/인테리어
912348,2017,4,강남구,삼성1동,1001496,CS300043,전자상거래업,8,8,0,0,0,0,0,25637222,25637222,18076747,7560475,9912656,15259305,소매,유통

In [ ]:
df_preprocessed.columns

Index(['기준_년_코드', '기준_분기_코드', '자치구', '행정동', '상권_코드', '서비스_업종_코드',
       '서비스_업종_코드_명', '점포_수', '유사_업종_점포_수', '개업_율', '개업_점포_수', '폐업_률',
       '폐업_점포_수', '프랜차이즈_점포_수', '총_매출_금액', '분기당_매출_금액', '주중_매출_금액', '주말_매출_금액',
       '남성_매출_금액', '여성_매출_금액', '대분류', '중분류'],
      dtype='object')

In [ ]:
# 필요한 컬럼만 추출
df_preprocessed = df_preprocessed[['기준_년_코드', '기준_분기_코드', '자치구', '행정동', '대분류', '중분류', '상권_코드', '서비스_업종_코드', '서비스_업종_코드_명', '점포_수', '유사_업종_점포_수',
                             '개업_율', '개업_점포_수', '폐업_률', '폐업_점포_수', '프랜차이즈_점포_수',
                             '총_매출_금액', '분기당_매출_금액', '주중_매출_금액', '주말_매출_금액', '남성_매출_금액', '여성_매출_금액']]
df_preprocessed.head()

,기준_년_코드,기준_분기_코드,자치구,행정동,대분류,중분류,상권_코드,서비스_업종_코드,서비스_업종_코드_명,점포_수,유사_업종_점포_수,개업_율,개업_점포_수,폐업_률,폐업_점포_수,프랜차이즈_점포_수,총_매출_금액,분기당_매출_금액,주중_매출_금액,주말_매출_금액,남성_매출_금액,여성_매출_금액
0,2022,4,영등포구,대림3동,소매,가구/인테리어,2120139,CS300031,가구,2,2,0,0,0,0,0,205619535,205619535,205619535,0,12549549,193069986
1,2022,4,중랑구,면목3.8동,외식,카페/베이커리,2120068,CS100005,제과점,3,5,20,1,0,0,2,1111094837,1111094837,759670537,351424300,405775472,623495718
2,2022,4,강동구,천호3동,소매,의료,2130322,CS300018,의약품,3,3,0,0,0,0,0,168879417,168879417,168879417,0,69665344,99214073
3,2022,4,송파구,석촌동,소매,의류/잡화,2120230,CS300017,시계및귀금속,4,5,0,0,0,0,1,47289011,47289011,47289011,0,7782781,39506230
4,2022,4,송파구,가락본동,서비스,오락,2120234,CS200016,당구장,11,12,0,0,0,0,1,191548486,191548486,117007334,74541152,171020276,15692619

In [ ]:
# 총 점포수 컬럼 추가
df_preprocessed['순점포증감률'] = (df_preprocessed['개업_점포_수'] - df_preprocessed['폐업_점포_수']) / df_preprocessed['유사_업종_점포_수']

# 컬럼 명 변경
df_preprocessed.rename(columns={'유사_업종_점포_수': '총_점포수'}, inplace=True)


df_preprocessed.head(1)

<ipython-input-18-6b4d00b9bbf8>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_preprocessed['순점포증감률'] = (df_preprocessed['개업_점포_수'] - df_preprocessed['폐업_점포_수']) / df_preprocessed['유사_업종_점포_수']
<ipython-input-18-6b4d00b9bbf8>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_preprocessed.rename(columns={'유사_업종_점포_수': '총_점포수'}, inplace=True)

,기준_년_코드,기준_분기_코드,자치구,행정동,대분류,중분류,상권_코드,서비스_업종_코드,서비스_업종_코드_명,점포_수,총_점포수,개업_율,개업_점포_수,폐업_률,폐업_점포_수,프랜차이즈_점포_수,총_매출_금액,분기당_매출_금액,주중_매출_금액,주말_매출_금액,남성_매출_금액,여성_매출_금액,순점포증감률
0,2022,4,영등포구,대림3동,소매,가구/인테리어,2120139,CS300031,가구,2,2,0,0,0,0,0,205619535,205619535,205619535,0,12549549,193069986,0.0

In [ ]:
df_preprocessed.columns

Index(['기준_년_코드', '기준_분기_코드', '자치구', '행정동', '대분류', '중분류', '상권_코드', '서비스_업종_코드',
       '서비스_업종_코드_명', '점포_수', '총_점포수', '개업_율', '개업_점포_수', '폐업_률', '폐업_점포_수',
       '프랜차이즈_점포_수', '총_매출_금액', '분기당_매출_금액', '주중_매출_금액', '주말_매출_금액',
       '남성_매출_금액', '여성_매출_금액', '순점포증감률'],
      dtype='object')

In [ ]:
df_preprocessed = df_preprocessed[['기준_년_코드', '기준_분기_코드', '자치구', '행정동', '대분류', '중분류', '상권_코드', '서비스_업종_코드', '서비스_업종_코드_명', '점포_수', '총_점포수', '순점포증감률', '개업_율', '개업_점포_수', '폐업_률', '폐업_점포_수',
                                   '프랜차이즈_점포_수', '총_매출_금액', '분기당_매출_금액', '주중_매출_금액', '주말_매출_금액', '남성_매출_금액', '여성_매출_금액']]
df_preprocessed.head(2)

,기준_년_코드,기준_분기_코드,자치구,행정동,대분류,중분류,상권_코드,서비스_업종_코드,서비스_업종_코드_명,점포_수,총_점포수,순점포증감률,개업_율,개업_점포_수,폐업_률,폐업_점포_수,프랜차이즈_점포_수,총_매출_금액,분기당_매출_금액,주중_매출_금액,주말_매출_금액,남성_매출_금액,여성_매출_금액
0,2022,4,영등포구,대림3동,소매,가구/인테리어,2120139,CS300031,가구,2,2,0.0,0,0,0,0,0,205619535,205619535,205619535,0,12549549,193069986
1,2022,4,중랑구,면목3.8동,외식,카페/베이커리,2120068,CS100005,제과점,3,5,0.2,20,1,0,0,2,1111094837,1111094837,759670537,351424300,405775472,623495718

In [ ]:
df_preprocessed.isnull().sum()

기준_년_코드        0
기준_분기_코드       0
자치구            0
행정동            0
대분류            0
중분류            0
상권_코드          0
서비스_업종_코드      0
서비스_업종_코드_명    0
점포_수           0
총_점포수          0
순점포증감률         3
개업_율           0
개업_점포_수        0
폐업_률           0
폐업_점포_수        0
프랜차이즈_점포_수     0
총_매출_금액        0
분기당_매출_금액      0
주중_매출_금액       0
주말_매출_금액       0
남성_매출_금액       0
여성_매출_금액       0
dtype: int64

In [ ]:
df_preprocessed[df_preprocessed['순점포증감률'].isna()]

,기준_년_코드,기준_분기_코드,자치구,행정동,대분류,중분류,상권_코드,서비스_업종_코드,서비스_업종_코드_명,점포_수,총_점포수,순점포증감률,개업_율,개업_점포_수,폐업_률,폐업_점포_수,프랜차이즈_점포_수,총_매출_금액,분기당_매출_금액,주중_매출_금액,주말_매출_금액,남성_매출_금액,여성_매출_금액
213155,2021,3,도봉구,방학3동,외식,식사류,2110386,CS100008,분식전문점,0,0,NaN,0,1,0,1,0,6396092,6396092,5568161,827931,2048682,4210136
214382,2021,3,노원구,상계3.4동,외식,식사류,2110437,CS100002,중식음식점,0,0,NaN,0,1,0,1,0,15000000,15000000,7861161,7138839,8840344,6159656
666023,2018,3,강서구,방화2동,서비스,미용,2110633,CS200030,피부관리실,0,0,NaN,0,1,0,1,0,4076642,4076642,3429991,646651,1535797,2540845

In [ ]:
# '순점포증감률' 열의 NaN 값을 0으로 변경
df_preprocessed['순점포증감률'] = df_preprocessed['순점포증감률'].fillna(0)
df_preprocessed[df_preprocessed['순점포증감률'].isna()]

Empty DataFrame
Columns: [기준_년_코드, 기준_분기_코드, 자치구, 행정동, 대분류, 중분류, 상권_코드, 서비스_업종_코드, 서비스_업종_코드_명, 점포_수, 총_점포수, 순점포증감률, 개업_율, 개업_점포_수, 폐업_률, 폐업_점포_수, 프랜차이즈_점포_수, 총_매출_금액, 분기당_매출_금액, 주중_매출_금액, 주말_매출_금액, 남성_매출_금액, 여성_매출_금액]
Index: []

In [ ]:
df_preprocessed.isnull().sum()

기준_년_코드        0
기준_분기_코드       0
자치구            0
행정동            0
대분류            0
중분류            0
상권_코드          0
서비스_업종_코드      0
서비스_업종_코드_명    0
점포_수           0
총_점포수          0
순점포증감률         0
개업_율           0
개업_점포_수        0
폐업_률           0
폐업_점포_수        0
프랜차이즈_점포_수     0
총_매출_금액        0
분기당_매출_금액      0
주중_매출_금액       0
주말_매출_금액       0
남성_매출_금액       0
여성_매출_금액       0
dtype: int64

In [ ]:
df_preprocessed

,기준_년_코드,기준_분기_코드,자치구,행정동,대분류,중분류,상권_코드,서비스_업종_코드,서비스_업종_코드_명,점포_수,총_점포수,순점포증감률,개업_율,개업_점포_수,폐업_률,폐업_점포_수,프랜차이즈_점포_수,총_매출_금액,분기당_매출_금액,주중_매출_금액,주말_매출_금액,남성_매출_금액,여성_매출_금액
0,2022,4,영등포구,대림3동,소매,가구/인테리어,2120139,CS300031,가구,2,2,0.0,0,0,0,0,0,205619535,205619535,205619535,0,12549549,193069986
1,2022,4,중랑구,면목3.8동,외식,카페/베이커리,2120068,CS100005,제과점,3,5,0.2,20,1,0,0,2,1111094837,1111094837,759670537,351424300,405775472,623495718
2,2022,4,강동구,천호3동,소매,의료,2130322,CS300018,의약품,3,3,0.0,0,0,0,0,0,168879417,168879417,168879417,0,69665344,99214073
3,2022,4,송파구,석촌동,소매,의류/잡화,2120230,CS300017,시계및귀금속,4,5,0.0,0,0,0,0,1,47289011,47289011,47289011,0,7782781,39506230
4,2022,4,송파구,가락본동,서비스,오락,2120234,CS200016,당구장,11,12,0.0,0,0,0,0,1,191548486,191548486,117007334,74541152,171020276,15692619
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
912344,2017,4,강남구,삼성1동,소매,가구/인테리어,1001496,CS300031,가구,9,9,0.0,0,0,0,0,0,330320365,330320365,303278487,27041878,114857625,116434465
912345,2017,4,강남구,삼성1동,소매,가구/인테리어,1001496,CS300032,가전제품,9,9,0.0,0,0,0,0,0,2174589379,2174589379,1601331971,573257408,966992622,787018046
912346,2017,4,강남구,삼성1동,소매,가구/인테리어,1001496,CS300035,인테리어,4,4,0.0,0,0,0,0,0,2839146155,2839146155,1871616983,967529172,695743479,2021268896
912347,2017,4,강남구,삼성1동,소매,가구/인테리어,1001496,CS300041,예술품,9,9,0.0,0,0,0,0,0,674145284,674145284,544184202,129961082,155488268,153880451
912348,2017,4,강남구,삼성1동,소매,유통,1001496,CS300043,전자상거래업,8,8,0.0,0,0,0,0,0,25637222,25637222,18076747,7560475,9912656,15259305

In [ ]:
df_preprocessed = df_preprocessed.sort_values(by=['기준_년_코드', '기준_분기_코드'], ascending=[False, True])
df_preprocessed.reset_index(drop=True, inplace=True)

df_preprocessed

,기준_년_코드,기준_분기_코드,자치구,행정동,대분류,중분류,상권_코드,서비스_업종_코드,서비스_업종_코드_명,점포_수,총_점포수,순점포증감률,개업_율,개업_점포_수,폐업_률,폐업_점포_수,프랜차이즈_점포_수,총_매출_금액,분기당_매출_금액,주중_매출_금액,주말_매출_금액,남성_매출_금액,여성_매출_금액
0,2022,1,서대문구,북가좌2동,서비스,의료,2110499,CS200008,한의원,1,1,0.000000,0,0,0,0,0,54003138,54003138,35504845,18498293,8791373,45211765
1,2022,1,노원구,공릉1동,소매,의류/잡화,2110433,CS300016,안경,1,1,0.000000,0,0,0,0,0,16150022,16150022,14674653,1475369,9906049,6243973
2,2022,1,마포구,성산1동,소매,전자기기,2110548,CS300003,컴퓨터및주변장치판매,4,4,0.000000,0,0,0,0,0,89813767,89813767,89813767,0,0,89813767
3,2022,1,은평구,대조동,서비스,미용,2110481,CS200030,피부관리실,3,3,0.333333,33,1,0,0,0,4619842,4619842,405102,4214740,405102,4214740
4,2022,1,영등포구,신길6동,서비스,교육,2110804,CS200003,예술학원,5,5,0.000000,0,0,0,0,0,5946480,5946480,5946480,0,0,5946480
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
912344,2017,4,강남구,삼성1동,소매,가구/인테리어,1001496,CS300031,가구,9,9,0.000000,0,0,0,0,0,330320365,330320365,303278487,27041878,114857625,116434465
912345,2017,4,강남구,삼성1동,소매,가구/인테리어,1001496,CS300032,가전제품,9,9,0.000000,0,0,0,0,0,2174589379,2174589379,1601331971,573257408,966992622,787018046
912346,2017,4,강남구,삼성1동,소매,가구/인테리어,1001496,CS300035,인테리어,4,4,0.000000,0,0,0,0,0,2839146155,2839146155,1871616983,967529172,695743479,2021268896
912347,2017,4,강남구,삼성1동,소매,가구/인테리어,1001496,CS300041,예술품,9,9,0.000000,0,0,0,0,0,674145284,674145284,544184202,129961082,155488268,153880451
912348,2017,4,강남구,삼성1동,소매,유통,1001496,CS300043,전자상거래업,8,8,0.000000,0,0,0,0,0,25637222,25637222,18076747,7560475,9912656,15259305

In [ ]:
# df_preprocessed.to_csv('/content/drive/MyDrive/MC_KDT/프로젝트/파이널프로젝트/데이터/0728_Seoul_상권만.csv', encoding='euc-kr')

## 데이터 추가 : 생활인구

In [ ]:
# 생활인구 데이터 로드
pop = pd.read_csv('/content/drive/MyDrive/MC_KDT/프로젝트/파이널프로젝트/데이터/서울시 상권분석서비스(상권-생활인구).csv', encoding='cp949')
pop

,기준 년코드,기준_분기_코드,상권_구분_코드_명,상권_코드,상권_코드_명,총_생활인구_수,남성_생활인구_수,여성_생활인구_수
0,2022,4,관광특구,1001496,강남 마이스 관광특구,112658,55901,56757
1,2022,4,관광특구,1001495,잠실 관광특구,3632727,1757144,1875581
2,2022,4,관광특구,1001494,종로?청계 관광특구,3957665,2127522,1830142
3,2022,4,관광특구,1001493,동대문패션타운 관광특구,3249964,1534697,1715268
4,2022,4,관광특구,1001492,명동 남대문 북창동 다동 무교동 관광특구,4667755,2345370,2322385
...,...,...,...,...,...,...,...,...
40036,2017,1,골목상권,2110005,세검정,143249,62982,80268
40037,2017,1,골목상권,2110004,대신고등학교,353902,156216,197686
40038,2017,1,골목상권,2110003,세검정초등학교,374027,166810,207216
40039,2017,1,골목상권,2110002,독립문역 1번,268151,117436,150714
40040,2017,1,골목상권,2110001,이북5도청사,148356,65549,82808

In [ ]:
# '기준 년코드' 컬럼 이름을 '기준_년_코드'로 변경
pop.rename(columns={'기준 년코드': '기준_년_코드'}, inplace=True)
pop.head()

,기준_년_코드,기준_분기_코드,상권_구분_코드_명,상권_코드,상권_코드_명,총_생활인구_수,남성_생활인구_수,여성_생활인구_수
0,2022,4,관광특구,1001496,강남 마이스 관광특구,112658,55901,56757
1,2022,4,관광특구,1001495,잠실 관광특구,3632727,1757144,1875581
2,2022,4,관광특구,1001494,종로?청계 관광특구,3957665,2127522,1830142
3,2022,4,관광특구,1001493,동대문패션타운 관광특구,3249964,1534697,1715268
4,2022,4,관광특구,1001492,명동 남대문 북창동 다동 무교동 관광특구,4667755,2345370,2322385

In [ ]:
# ### 상권코드로 합치면 업종별로 데이터가 중복되어 중단
# df_merged2 = pd.merge(df_preprocessed, pop[['기준_년_코드', '기준_분기_코드', '상권_코드', '총_생활인구_수', '남성_생활인구_수', '여성_생활인구_수']], on=['기준_년_코드', '기준_분기_코드', '상권_코드'], how='inner')

# # 결과 확인
# df_merged2

In [ ]:
# # 데이터 확인용 --> ex. '상권_코드'가 1001496일 경우 뭐가 나오나
# df_merged2 = df_merged2[df_merged2['상권_코드'] == 1001496]

# df_merged2.head()

## 데이터 추가 : 지출

In [ ]:
expense = pd.read_csv('/content/drive/MyDrive/MC_KDT/프로젝트/파이널프로젝트/데이터/서울시 상권분석서비스(상권-소득소비).csv', encoding='cp949')
expense

,기준_년_코드,기준_분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,월_평균_소득_금액,소득_구간_코드,지출_총금액,식료품_지출_총금액,의류_신발_지출_총금액,생활용품_지출_총금액,의료비_지출_총금액,교통_지출_총금액,여가_지출_총금액,문화_지출_총금액,교육_지출_총금액,유흥_지출_총금액
0,2022,4,A,골목상권,2110001,이북5도청사,4305934.0,8.0,5.204276e+08,1.291260e+08,64853632.0,37122367.0,65974602.0,8.834376e+07,22223650.0,14656697.0,7.618534e+07,21941557.0
1,2022,4,A,골목상권,2110002,독립문역 1번,3463885.0,7.0,2.324652e+08,5.499899e+07,28932090.0,17084860.0,28271372.0,4.093308e+07,10180461.0,6575012.0,3.580528e+07,9684061.0
2,2022,4,A,골목상권,2110003,세검정초등학교,3548020.0,7.0,1.349699e+09,3.367042e+08,166150296.0,98720958.0,170559024.0,2.273671e+08,54707608.0,39088030.0,1.992198e+08,57182240.0
3,2022,4,A,골목상권,2110004,대신고등학교,2644953.0,6.0,7.127728e+08,2.056497e+08,84170011.0,51668351.0,100817261.0,1.118437e+08,23406627.0,22615164.0,8.286516e+07,29736776.0
4,2022,4,A,골목상권,2110005,세검정,3703145.0,7.0,8.847016e+08,2.214469e+08,109882417.0,64738346.0,111988892.0,1.498229e+08,37478670.0,25606895.0,1.265444e+08,37192149.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39077,2017,1,U,관광특구,1001492,명동 남대문 북창동 다동 무교동 관광특구,3374268.0,7.0,3.927186e+08,1.087167e+08,50613591.0,31629067.0,57724736.0,6.835523e+07,18120779.0,12007946.0,2.774372e+07,17806813.0
39078,2017,1,U,관광특구,1001493,동대문패션타운 관광특구,3703242.0,7.0,2.575916e+09,5.718456e+08,331658370.0,216948420.0,284618706.0,4.328987e+08,133108260.0,78089725.0,4.192844e+08,107463896.0
39079,2017,1,U,관광특구,1001494,종로?청계 관광특구,2350877.0,5.0,2.640514e+09,7.498735e+08,329659514.0,205602917.0,379663271.0,4.201432e+08,120789050.0,82279604.0,2.429368e+08,109565869.0
39080,2017,1,U,관광특구,1001495,잠실 관광특구,4738833.0,8.0,7.600040e+09,1.816018e+09,959308913.0,601365457.0,893135612.0,1.340093e+09,335563062.0,228534622.0,1.095590e+09,330430397.0
39081,2017,1,U,관광특구,1001496,강남 마이스 관광특구,5003931.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# ### '서비스_업종_코드_명'(업종명)에 따라 중분류 채우기

# # 중분류 컬럼 생성
# df_preprocessed['중분류'] = ''

# # 조건에 따라 '중분류' 열의 값을 채움
# for index, row in df_preprocessed.iterrows():
#     mask = mid_category['업종명'] == row['서비스_업종_코드_명']
#     matching_data = mid_category[mask]
#     if not matching_data.empty:
#         df_preprocessed.at[index, '중분류'] = matching_data['중분류'].values[0]

# df_preprocessed

In [ ]:
# df_preprocessed.columns

### 컬럼순서 및 이름 바꾸기

In [ ]:
# ### 컬럼 순서 바꾸고 컬럼명 변경
# df_preprocessed = df_preprocessed[['기준_년_코드', '기준_분기_코드', '자치구', '행정동', '중분류',
#                                    '서비스_업종_코드_명', '점포_수', '유사_업종_점포_수', '개업_율', '개업_점포_수', '폐업_률', '폐업_점포_수', '프랜차이즈_점포_수',
#                                    '분기당_매출_금액', '분기당_매출_건수',
#                                    '주중_매출_금액', '주말_매출_금액', '월요일_매출_금액','화요일_매출_금액', '수요일_매출_금액', '목요일_매출_금액', '금요일_매출_금액', '토요일_매출_금액', '일요일_매출_금액',
#                                    '시간대_00~06_매출_금액', '시간대_06~11_매출_금액', '시간대_11~14_매출_금액', '시간대_14~17_매출_금액', '시간대_17~21_매출_금액', '시간대_21~24_매출_금액', '남성_매출_금액', '여성_매출_금액',
#                                    '주중_매출_건수', '주말_매출_건수', '월요일_매출_건수', '화요일_매출_건수', '수요일_매출_건수', '목요일_매출_건수', '금요일_매출_건수', '토요일_매출_건수', '일요일_매출_건수',
#                                    '시간대_건수~06_매출_건수','시간대_건수~11_매출_건수', '시간대_건수~14_매출_건수', '시간대_건수~17_매출_건수', '시간대_건수~21_매출_건수', '시간대_건수~24_매출_건수',
#                                    '남성_매출_건수', '여성_매출_건수',
#                                    '주중_매출_비율', '주말_매출_비율', '월요일_매출_비율', '화요일_매출_비율', '수요일_매출_비율', '목요일_매출_비율', '금요일_매출_비율', '토요일_매출_비율', '일요일_매출_비율',
#                                    '시간대_00~06_매출_비율', '시간대_06~11_매출_비율', '시간대_11~14_매출_비율', '시간대_14~17_매출_비율', '시간대_17~21_매출_비율', '시간대_21~24_매출_비율',
#                                    '남성_매출_비율', '여성_매출_비율']]

# # 컬럼명 변경
# df = df_preprocessed.rename(columns = {'기준_년_코드':'기준_년',
#                                        '기준_분기_코드':'기준_분기',
#                                        '서비스_업종_코드_명':'업종명',
#                                        '유사_업종_점포_수':'총_점포수',
#                                        '개업_율':'개업률',
#                                        '폐업_률':'폐업률',
#                                        '시간대_00~06_매출_금액':'00~06시_매출금액', '시간대_06~11_매출_금액':'06~11시_매출금액', '시간대_11~14_매출_금액':'11~14시_매출금액',
#                                        '시간대_14~17_매출_금액':'14~17시_매출금액', '시간대_17~21_매출_금액':'17~21시_매출금액', '시간대_21~24_매출_금액':'21~24시_매출금액'})

# df.head()

# 전처리 파일 확인

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/MC_KDT/프로젝트/파이널프로젝트/데이터/0727_Seoul_preprocessed.csv', encoding='cp949', index_col=0)
df

,기준_년_코드,기준_분기_코드,자치구,행정동,대분류,중분류,상권_코드,서비스_업종_코드,서비스_업종_코드_명,점포_수,총_점포수,순점포증감률,개업_율,개업_점포_수,폐업_률,폐업_점포_수,프랜차이즈_점포_수,총_매출_금액,분기당_매출_금액,주중_매출_금액,주말_매출_금액,남성_매출_금액,여성_매출_금액
0,2022,4,영등포구,대림3동,소매,가구/인테리어,2120139,CS300031,가구,2,2,0.0,0,0,0,0,0,205619535,205619535,205619535,0,12549549,193069986
1,2022,4,중랑구,면목3.8동,외식,카페/베이커리,2120068,CS100005,제과점,3,5,0.2,20,1,0,0,2,1111094837,1111094837,759670537,351424300,405775472,623495718
2,2022,4,강동구,천호3동,소매,의료,2130322,CS300018,의약품,3,3,0.0,0,0,0,0,0,168879417,168879417,168879417,0,69665344,99214073
3,2022,4,송파구,석촌동,소매,의류/잡화,2120230,CS300017,시계및귀금속,4,5,0.0,0,0,0,0,1,47289011,47289011,47289011,0,7782781,39506230
4,2022,4,송파구,가락본동,서비스,오락,2120234,CS200016,당구장,11,12,0.0,0,0,0,0,1,191548486,191548486,117007334,74541152,171020276,15692619
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
912344,2017,4,강남구,삼성1동,소매,가구/인테리어,1001496,CS300031,가구,9,9,0.0,0,0,0,0,0,330320365,330320365,303278487,27041878,114857625,116434465
912345,2017,4,강남구,삼성1동,소매,가구/인테리어,1001496,CS300032,가전제품,9,9,0.0,0,0,0,0,0,2174589379,2174589379,1601331971,573257408,966992622,787018046
912346,2017,4,강남구,삼성1동,소매,가구/인테리어,1001496,CS300035,인테리어,4,4,0.0,0,0,0,0,0,2839146155,2839146155,1871616983,967529172,695743479,2021268896
912347,2017,4,강남구,삼성1동,소매,가구/인테리어,1001496,CS300041,예술품,9,9,0.0,0,0,0,0,0,674145284,674145284,544184202,129961082,155488268,153880451
912348,2017,4,강남구,삼성1동,소매,유통,1001496,CS300043,전자상거래업,8,8,0.0,0,0,0,0,0,25637222,25637222,18076747,7560475,9912656,15259305

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 912349 entries, 0 to 912348
Data columns (total 23 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   기준_년_코드      912349 non-null  int64
 1   기준_분기_코드     912349 non-null  int64
 2   자치구          912349 non-null  object
 3   행정동          912349 non-null  object
 4   대분류          912349 non-null  object
 5   중분류          912349 non-null  object
 6   상권_코드        912349 non-null  int64
 7   서비스_업종_코드    912349 non-null  object
 8   서비스_업종_코드_명  912349 non-null  object
 9   점포_수         912349 non-null  int64
 10  총_점포수        912349 non-null  int64
 11  순점포증감률       912346 non-null  float64
 12  개업_율         912349 non-null  int64
 13  개업_점포_수      912349 non-null  int64
 14  폐업_률         912349 non-null  int64
 15  폐업_점포_수      912349 non-null  int64
 16  프랜차이즈_점포_수   912349 non-null  int64
 17  총_매출_금액      912349 non-null  int64
 18  분기당_매출_금액    912349 non-null  int64
 19  주중_매출_금액     912349 non-null  int64
 20  주말_매출_금액     912349 non-null  int64
 21  남성_매출_금액     912349 non-null  int64
 22  여성_매출_금액     912349 non-null  int64
dtypes: float64(1), int64(16), object(6)
memory usage: 167.1+ MB

In [ ]:
import numpy as np
df.isnull().sum()

기준_년_코드        0
기준_분기_코드       0
자치구            0
행정동            0
대분류            0
중분류            0
상권_코드          0
서비스_업종_코드      0
서비스_업종_코드_명    0
점포_수           0
총_점포수          0
순점포증감률         0
개업_율           0
개업_점포_수        0
폐업_률           0
폐업_점포_수        0
프랜차이즈_점포_수     0
총_매출_금액        0
분기당_매출_금액      0
주중_매출_금액       0
주말_매출_금액       0
남성_매출_금액       0
여성_매출_금액       0
dtype: int64

In [ ]:
# null 값이 있는 행 추출
df_with_null = df[df.isnull().any(axis=1)]
df_with_null

,기준_년_코드,기준_분기_코드,자치구,행정동,대분류,중분류,상권_코드,서비스_업종_코드,서비스_업종_코드_명,점포_수,총_점포수,순점포증감률,개업_율,개업_점포_수,폐업_률,폐업_점포_수,프랜차이즈_점포_수,총_매출_금액,분기당_매출_금액,주중_매출_금액,주말_매출_금액,남성_매출_금액,여성_매출_금액
213155,2021,3,도봉구,방학3동,외식,식사류,2110386,CS100008,분식전문점,0,0,NaN,0,1,0,1,0,6396092,6396092,5568161,827931,2048682,4210136
214382,2021,3,노원구,상계3.4동,외식,식사류,2110437,CS100002,중식음식점,0,0,NaN,0,1,0,1,0,15000000,15000000,7861161,7138839,8840344,6159656
666023,2018,3,강서구,방화2동,서비스,미용,2110633,CS200030,피부관리실,0,0,NaN,0,1,0,1,0,4076642,4076642,3429991,646651,1535797,2540845

In [ ]:
df_with_null.서비스_업종_코드_명.value_counts()

분식전문점    1
중식음식점    1
피부관리실    1
Name: 서비스_업종_코드_명, dtype: int64

In [ ]:
df_with_null[df_with_null['서비스_업종_코드_명'] == '피부관리실']

,기준_년_코드,기준_분기_코드,자치구,행정동,대분류,중분류,상권_코드,서비스_업종_코드,서비스_업종_코드_명,점포_수,총_점포수,순점포증감률,개업_율,개업_점포_수,폐업_률,폐업_점포_수,프랜차이즈_점포_수,총_매출_금액,분기당_매출_금액,주중_매출_금액,주말_매출_금액,남성_매출_금액,여성_매출_금액
666023,2018,3,강서구,방화2동,서비스,미용,2110633,CS200030,피부관리실,0,0,NaN,0,1,0,1,0,4076642,4076642,3429991,646651,1535797,2540845

In [ ]:
# len(df[df['서비스_업종_코드_명'] == '피부관리실'])

In [ ]:
df.loc[666023, '순점포증감률']

nan

In [ ]:
df[df['순점포증감률'].isna()]

,기준_년_코드,기준_분기_코드,자치구,행정동,대분류,중분류,상권_코드,서비스_업종_코드,서비스_업종_코드_명,점포_수,총_점포수,순점포증감률,개업_율,개업_점포_수,폐업_률,폐업_점포_수,프랜차이즈_점포_수,총_매출_금액,분기당_매출_금액,주중_매출_금액,주말_매출_금액,남성_매출_금액,여성_매출_금액
213155,2021,3,도봉구,방학3동,외식,식사류,2110386,CS100008,분식전문점,0,0,NaN,0,1,0,1,0,6396092,6396092,5568161,827931,2048682,4210136
214382,2021,3,노원구,상계3.4동,외식,식사류,2110437,CS100002,중식음식점,0,0,NaN,0,1,0,1,0,15000000,15000000,7861161,7138839,8840344,6159656
666023,2018,3,강서구,방화2동,서비스,미용,2110633,CS200030,피부관리실,0,0,NaN,0,1,0,1,0,4076642,4076642,3429991,646651,1535797,2540845

In [ ]:
# '순점포증감률' 열의 NaN 값을 0으로 변경
df['순점포증감률'] = df['순점포증감률'].fillna(0)
df[df['순점포증감률'].isna()]

Empty DataFrame
Columns: [기준_년_코드, 기준_분기_코드, 자치구, 행정동, 대분류, 중분류, 상권_코드, 서비스_업종_코드, 서비스_업종_코드_명, 점포_수, 총_점포수, 순점포증감률, 개업_율, 개업_점포_수, 폐업_률, 폐업_점포_수, 프랜차이즈_점포_수, 총_매출_금액, 분기당_매출_금액, 주중_매출_금액, 주말_매출_금액, 남성_매출_금액, 여성_매출_금액]
Index: []

In [ ]:
df.isnull().sum()

기준_년_코드        0
기준_분기_코드       0
자치구            0
행정동            0
대분류            0
중분류            0
상권_코드          0
서비스_업종_코드      0
서비스_업종_코드_명    0
점포_수           0
총_점포수          0
순점포증감률         0
개업_율           0
개업_점포_수        0
폐업_률           0
폐업_점포_수        0
프랜차이즈_점포_수     0
총_매출_금액        0
분기당_매출_금액      0
주중_매출_금액       0
주말_매출_금액       0
남성_매출_금액       0
여성_매출_금액       0
dtype: int64

In [ ]:
# df.to_csv('/content/drive/MyDrive/MC_KDT/프로젝트/파이널프로젝트/데이터/0727_Seoul_preprocessed.csv', encoding='euc-kr')

In [ ]:
double_check = pd.read_csv('/content/drive/MyDrive/MC_KDT/프로젝트/파이널프로젝트/데이터/0727_Seoul_preprocessed.csv', encoding='cp949', index_col=0)
double_check

,기준_년_코드,기준_분기_코드,자치구,행정동,대분류,중분류,상권_코드,서비스_업종_코드,서비스_업종_코드_명,점포_수,총_점포수,순점포증감률,개업_율,개업_점포_수,폐업_률,폐업_점포_수,프랜차이즈_점포_수,총_매출_금액,분기당_매출_금액,주중_매출_금액,주말_매출_금액,남성_매출_금액,여성_매출_금액
0,2022,4,영등포구,대림3동,소매,가구/인테리어,2120139,CS300031,가구,2,2,0.0,0,0,0,0,0,205619535,205619535,205619535,0,12549549,193069986
1,2022,4,중랑구,면목3.8동,외식,카페/베이커리,2120068,CS100005,제과점,3,5,0.2,20,1,0,0,2,1111094837,1111094837,759670537,351424300,405775472,623495718
2,2022,4,강동구,천호3동,소매,의료,2130322,CS300018,의약품,3,3,0.0,0,0,0,0,0,168879417,168879417,168879417,0,69665344,99214073
3,2022,4,송파구,석촌동,소매,의류/잡화,2120230,CS300017,시계및귀금속,4,5,0.0,0,0,0,0,1,47289011,47289011,47289011,0,7782781,39506230
4,2022,4,송파구,가락본동,서비스,오락,2120234,CS200016,당구장,11,12,0.0,0,0,0,0,1,191548486,191548486,117007334,74541152,171020276,15692619
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
912344,2017,4,강남구,삼성1동,소매,가구/인테리어,1001496,CS300031,가구,9,9,0.0,0,0,0,0,0,330320365,330320365,303278487,27041878,114857625,116434465
912345,2017,4,강남구,삼성1동,소매,가구/인테리어,1001496,CS300032,가전제품,9,9,0.0,0,0,0,0,0,2174589379,2174589379,1601331971,573257408,966992622,787018046
912346,2017,4,강남구,삼성1동,소매,가구/인테리어,1001496,CS300035,인테리어,4,4,0.0,0,0,0,0,0,2839146155,2839146155,1871616983,967529172,695743479,2021268896
912347,2017,4,강남구,삼성1동,소매,가구/인테리어,1001496,CS300041,예술품,9,9,0.0,0,0,0,0,0,674145284,674145284,544184202,129961082,155488268,153880451
912348,2017,4,강남구,삼성1동,소매,유통,1001496,CS300043,전자상거래업,8,8,0.0,0,0,0,0,0,25637222,25637222,18076747,7560475,9912656,15259305

In [ ]:
double_check.isnull().sum()

기준_년_코드        0
기준_분기_코드       0
자치구            0
행정동            0
대분류            0
중분류            0
상권_코드          0
서비스_업종_코드      0
서비스_업종_코드_명    0
점포_수           0
총_점포수          0
순점포증감률         0
개업_율           0
개업_점포_수        0
폐업_률           0
폐업_점포_수        0
프랜차이즈_점포_수     0
총_매출_금액        0
분기당_매출_금액      0
주중_매출_금액       0
주말_매출_금액       0
남성_매출_금액       0
여성_매출_금액       0
dtype: int64

# "스포츠강습" 띄어쓰기 처리

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/MC_KDT/프로젝트/파이널프로젝트/데이터/0727_Seoul_preprocessed.csv', encoding='cp949', index_col=0)
df

,기준_년_코드,기준_분기_코드,자치구,행정동,대분류,중분류,상권_코드,서비스_업종_코드,서비스_업종_코드_명,점포_수,총_점포수,순점포증감률,개업_율,개업_점포_수,폐업_률,폐업_점포_수,프랜차이즈_점포_수,총_매출_금액,분기당_매출_금액,주중_매출_금액,주말_매출_금액,남성_매출_금액,여성_매출_금액
0,2022,4,영등포구,대림3동,소매,가구/인테리어,2120139,CS300031,가구,2,2,0.0,0,0,0,0,0,205619535,205619535,205619535,0,12549549,193069986
1,2022,4,중랑구,면목3.8동,외식,카페/베이커리,2120068,CS100005,제과점,3,5,0.2,20,1,0,0,2,1111094837,1111094837,759670537,351424300,405775472,623495718
2,2022,4,강동구,천호3동,소매,의료,2130322,CS300018,의약품,3,3,0.0,0,0,0,0,0,168879417,168879417,168879417,0,69665344,99214073
3,2022,4,송파구,석촌동,소매,의류/잡화,2120230,CS300017,시계및귀금속,4,5,0.0,0,0,0,0,1,47289011,47289011,47289011,0,7782781,39506230
4,2022,4,송파구,가락본동,서비스,오락,2120234,CS200016,당구장,11,12,0.0,0,0,0,0,1,191548486,191548486,117007334,74541152,171020276,15692619
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
912344,2017,4,강남구,삼성1동,소매,가구/인테리어,1001496,CS300031,가구,9,9,0.0,0,0,0,0,0,330320365,330320365,303278487,27041878,114857625,116434465
912345,2017,4,강남구,삼성1동,소매,가구/인테리어,1001496,CS300032,가전제품,9,9,0.0,0,0,0,0,0,2174589379,2174589379,1601331971,573257408,966992622,787018046
912346,2017,4,강남구,삼성1동,소매,가구/인테리어,1001496,CS300035,인테리어,4,4,0.0,0,0,0,0,0,2839146155,2839146155,1871616983,967529172,695743479,2021268896
912347,2017,4,강남구,삼성1동,소매,가구/인테리어,1001496,CS300041,예술품,9,9,0.0,0,0,0,0,0,674145284,674145284,544184202,129961082,155488268,153880451
912348,2017,4,강남구,삼성1동,소매,유통,1001496,CS300043,전자상거래업,8,8,0.0,0,0,0,0,0,25637222,25637222,18076747,7560475,9912656,15259305

In [ ]:
df[df['서비스_업종_코드_명'] == '스포츠강습']

Empty DataFrame
Columns: [기준_년_코드, 기준_분기_코드, 자치구, 행정동, 대분류, 중분류, 상권_코드, 서비스_업종_코드, 서비스_업종_코드_명, 점포_수, 총_점포수, 순점포증감률, 개업_율, 개업_점포_수, 폐업_률, 폐업_점포_수, 프랜차이즈_점포_수, 총_매출_금액, 분기당_매출_금액, 주중_매출_금액, 주말_매출_금액, 남성_매출_금액, 여성_매출_금액]
Index: []

In [ ]:
df.서비스_업종_코드_명.unique()

array(['가구', '제과점', '의약품', '시계및귀금속', '당구장', '중식음식점', '노래방', '패스트푸드점',
       '여관', '신발', '한의원', '자동차수리', '애완동물', '외국어학원', 'PC방', '예술학원', '화초',
       '치킨전문점', '고시원', '안경', '스포츠 강습', '핸드폰', '편의점', '문구', '치과의원',
       '스포츠클럽', '섬유제품', '미용실', '분식전문점', '운동/경기용품', '일반의원', '일식음식점',
       '반찬가게', '피부관리실', '인테리어', '완구', '철물점', '일반교습학원', '양식음식점', '일반의류',
       '컴퓨터및주변장치판매', '서적', '전자상거래업', '슈퍼마켓', '부동산중개업', '호프-간이주점', '한식음식점',
       '세탁소', '화장품', '조명용품', '골프연습장', '가전제품', '커피-음료', '미곡판매', '청과상',
       '수산물판매', '육류판매', '자동차미용', '의료기기', '가전제품수리', '가방', '네일숍',
       '자전거 및 기타운송장비', '예술품', '여행사', '주유소', '독서실', '사진관', '한복점', '악기',
       '회계사사무소', '세무사사무소', '유아의류', '자동차부품', '볼링장', '통신기기수리', '중고차판매',
       '비디오/서적임대', '법무사사무소', '변호사사무소', '건축물청소'], dtype=object)

In [ ]:
df['서비스_업종_코드_명'] = df['서비스_업종_코드_명'].replace('스포츠 강습', '스포츠강습')
df[df['서비스_업종_코드_명'] == '스포츠 강습']

Empty DataFrame
Columns: [기준_년_코드, 기준_분기_코드, 자치구, 행정동, 대분류, 중분류, 상권_코드, 서비스_업종_코드, 서비스_업종_코드_명, 점포_수, 총_점포수, 순점포증감률, 개업_율, 개업_점포_수, 폐업_률, 폐업_점포_수, 프랜차이즈_점포_수, 총_매출_금액, 분기당_매출_금액, 주중_매출_금액, 주말_매출_금액, 남성_매출_금액, 여성_매출_금액]
Index: []

In [ ]:
df[df['서비스_업종_코드_명'] == '스포츠강습']

,기준_년_코드,기준_분기_코드,자치구,행정동,대분류,중분류,상권_코드,서비스_업종_코드,서비스_업종_코드_명,점포_수,총_점포수,순점포증감률,개업_율,개업_점포_수,폐업_률,폐업_점포_수,프랜차이즈_점포_수,총_매출_금액,분기당_매출_금액,주중_매출_금액,주말_매출_금액,남성_매출_금액,여성_매출_금액
21,2022,4,중구,청구동,서비스,교육,2110054,CS200005,스포츠강습,1,1,0.000000,0,0,0,0,0,4044944,4044944,0,4044944,4044944,0
75,2022,4,광진구,자양4동,서비스,교육,2110140,CS200005,스포츠강습,6,6,0.000000,0,0,0,0,0,979071,979071,979071,0,979071,0
182,2022,4,강남구,대치2동,서비스,교육,2120222,CS200005,스포츠강습,9,9,0.000000,0,0,0,0,0,154058226,154058226,154058226,0,27997732,115066436
190,2022,4,금천구,가산동,서비스,교육,2120131,CS200005,스포츠강습,10,12,0.000000,0,0,0,0,2,390902801,390902801,390902801,0,93044135,210369025
201,2022,4,송파구,잠실본동,서비스,교육,2120225,CS200005,스포츠강습,33,35,0.028571,6,2,3,1,2,1751225900,1751225900,1534518937,216706963,778736785,862153166
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
912017,2017,4,용산구,이태원1동,서비스,교육,1001491,CS200005,스포츠강습,3,3,0.000000,0,0,0,0,0,56054100,56054100,46569481,9484619,22585249,30095883
912075,2017,4,중구,소공동,서비스,교육,1001492,CS200005,스포츠강습,6,6,0.000000,17,1,17,1,0,461252486,461252486,461252486,0,32048843,377052715
912139,2017,4,중구,광희동,서비스,교육,1001493,CS200005,스포츠강습,3,3,-0.333333,0,0,33,1,0,36695109,36695109,36695109,0,3573340,30939818
912200,2017,4,종로구,종로1.2.3.4가동,서비스,교육,1001494,CS200005,스포츠강습,9,10,0.000000,0,0,0,0,1,306927497,306927497,301035933,5891564,108184983,192380412
912265,2017,4,송파구,오륜동,서비스,교육,1001495,CS200005,스포츠강습,15,15,0.066667,7,1,0,0,0,561970170,561970170,484647379,77322791,99931773,399808404

In [ ]:
df.columns

Index(['기준_년_코드', '기준_분기_코드', '자치구', '행정동', '대분류', '중분류', '상권_코드', '서비스_업종_코드',
       '서비스_업종_코드_명', '점포_수', '총_점포수', '순점포증감률', '개업_율', '개업_점포_수', '폐업_률',
       '폐업_점포_수', '프랜차이즈_점포_수', '총_매출_금액', '분기당_매출_금액', '주중_매출_금액', '주말_매출_금액',
       '남성_매출_금액', '여성_매출_금액'],
      dtype='object')

In [ ]:
# 컬럼명 변경
df = df.rename(columns = {'서비스_업종_코드_명':'업종명'})

In [ ]:
df.columns

Index(['기준_년_코드', '기준_분기_코드', '자치구', '행정동', '대분류', '중분류', '상권_코드', '서비스_업종_코드',
       '업종명', '점포_수', '총_점포수', '순점포증감률', '개업_율', '개업_점포_수', '폐업_률', '폐업_점포_수',
       '프랜차이즈_점포_수', '총_매출_금액', '분기당_매출_금액', '주중_매출_금액', '주말_매출_금액',
       '남성_매출_금액', '여성_매출_금액'],
      dtype='object')

In [ ]:
# 필요한 컬럼만 추출
df = df[['기준_년_코드', '기준_분기_코드', '자치구', '행정동', '대분류', '상권_코드', '중분류', '업종명', '총_점포수', '점포_수', '순점포증감률', '개업_율', '개업_점포_수', '폐업_률',
         '폐업_점포_수', '프랜차이즈_점포_수', '총_매출_금액', '분기당_매출_금액', '주중_매출_금액', '주말_매출_금액', '남성_매출_금액', '여성_매출_금액']]
print(df.shape)
df.head(2)

(912349, 22)

,기준_년_코드,기준_분기_코드,자치구,행정동,대분류,상권_코드,중분류,업종명,총_점포수,점포_수,순점포증감률,개업_율,개업_점포_수,폐업_률,폐업_점포_수,프랜차이즈_점포_수,총_매출_금액,분기당_매출_금액,주중_매출_금액,주말_매출_금액,남성_매출_금액,여성_매출_금액
0,2022,4,영등포구,대림3동,소매,2120139,가구/인테리어,가구,2,2,0.0,0,0,0,0,0,205619535,205619535,205619535,0,12549549,193069986
1,2022,4,중랑구,면목3.8동,외식,2120068,카페/베이커리,제과점,5,3,0.2,20,1,0,0,2,1111094837,1111094837,759670537,351424300,405775472,623495718

In [ ]:
df.isnull().sum()

기준_년_코드       0
기준_분기_코드      0
자치구           0
행정동           0
대분류           0
상권_코드         0
중분류           0
업종명           0
총_점포수         0
점포_수          0
순점포증감률        0
개업_율          0
개업_점포_수       0
폐업_률          0
폐업_점포_수       0
프랜차이즈_점포_수    0
총_매출_금액       0
분기당_매출_금액     0
주중_매출_금액      0
주말_매출_금액      0
남성_매출_금액      0
여성_매출_금액      0
dtype: int64

In [ ]:
# df.to_csv('/content/drive/MyDrive/MC_KDT/프로젝트/파이널프로젝트/데이터/0727_Seoul_preprocessed.csv', encoding='euc-kr')

# 전처리 최종_컬럼 순서 바꾸기

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/MC_KDT/프로젝트/파이널프로젝트/데이터/0727_Seoul_preprocessed.csv', encoding='cp949', index_col=0)
df

,기준_년_코드,기준_분기_코드,자치구,행정동,대분류,상권_코드,중분류,업종명,총_점포수,점포_수,순점포증감률,개업_율,개업_점포_수,폐업_률,폐업_점포_수,프랜차이즈_점포_수,총_매출_금액,분기당_매출_금액,주중_매출_금액,주말_매출_금액,남성_매출_금액,여성_매출_금액
101760,2022,1,서대문구,북가좌2동,서비스,2110499,의료,한의원,1,1,0.000000,0,0,0,0,0,54003138,54003138,35504845,18498293,8791373,45211765
101761,2022,1,노원구,공릉1동,소매,2110433,의류/잡화,안경,1,1,0.000000,0,0,0,0,0,16150022,16150022,14674653,1475369,9906049,6243973
101762,2022,1,마포구,성산1동,소매,2110548,전자기기,컴퓨터및주변장치판매,4,4,0.000000,0,0,0,0,0,89813767,89813767,89813767,0,0,89813767
101763,2022,1,은평구,대조동,서비스,2110481,미용,피부관리실,3,3,0.333333,33,1,0,0,0,4619842,4619842,405102,4214740,405102,4214740
101764,2022,1,영등포구,신길6동,서비스,2110804,교육,예술학원,5,5,0.000000,0,0,0,0,0,5946480,5946480,5946480,0,0,5946480
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
912344,2017,4,강남구,삼성1동,소매,1001496,가구/인테리어,가구,9,9,0.000000,0,0,0,0,0,330320365,330320365,303278487,27041878,114857625,116434465
912345,2017,4,강남구,삼성1동,소매,1001496,가구/인테리어,가전제품,9,9,0.000000,0,0,0,0,0,2174589379,2174589379,1601331971,573257408,966992622,787018046
912346,2017,4,강남구,삼성1동,소매,1001496,가구/인테리어,인테리어,4,4,0.000000,0,0,0,0,0,2839146155,2839146155,1871616983,967529172,695743479,2021268896
912347,2017,4,강남구,삼성1동,소매,1001496,가구/인테리어,예술품,9,9,0.000000,0,0,0,0,0,674145284,674145284,544184202,129961082,155488268,153880451
912348,2017,4,강남구,삼성1동,소매,1001496,유통,전자상거래업,8,8,0.000000,0,0,0,0,0,25637222,25637222,18076747,7560475,9912656,15259305

In [ ]:
new_df = df.copy()
df_sorted = new_df.sort_values(by=['기준_년_코드', '기준_분기_코드'], ascending=[False, True])
df_sorted.reset_index(drop=True, inplace=True)

df_sorted

,기준_년_코드,기준_분기_코드,자치구,행정동,대분류,상권_코드,중분류,업종명,총_점포수,점포_수,순점포증감률,개업_율,개업_점포_수,폐업_률,폐업_점포_수,프랜차이즈_점포_수,총_매출_금액,분기당_매출_금액,주중_매출_금액,주말_매출_금액,남성_매출_금액,여성_매출_금액
0,2022,1,서대문구,북가좌2동,서비스,2110499,의료,한의원,1,1,0.000000,0,0,0,0,0,54003138,54003138,35504845,18498293,8791373,45211765
1,2022,1,노원구,공릉1동,소매,2110433,의류/잡화,안경,1,1,0.000000,0,0,0,0,0,16150022,16150022,14674653,1475369,9906049,6243973
2,2022,1,마포구,성산1동,소매,2110548,전자기기,컴퓨터및주변장치판매,4,4,0.000000,0,0,0,0,0,89813767,89813767,89813767,0,0,89813767
3,2022,1,은평구,대조동,서비스,2110481,미용,피부관리실,3,3,0.333333,33,1,0,0,0,4619842,4619842,405102,4214740,405102,4214740
4,2022,1,영등포구,신길6동,서비스,2110804,교육,예술학원,5,5,0.000000,0,0,0,0,0,5946480,5946480,5946480,0,0,5946480
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
912344,2017,4,강남구,삼성1동,소매,1001496,가구/인테리어,가구,9,9,0.000000,0,0,0,0,0,330320365,330320365,303278487,27041878,114857625,116434465
912345,2017,4,강남구,삼성1동,소매,1001496,가구/인테리어,가전제품,9,9,0.000000,0,0,0,0,0,2174589379,2174589379,1601331971,573257408,966992622,787018046
912346,2017,4,강남구,삼성1동,소매,1001496,가구/인테리어,인테리어,4,4,0.000000,0,0,0,0,0,2839146155,2839146155,1871616983,967529172,695743479,2021268896
912347,2017,4,강남구,삼성1동,소매,1001496,가구/인테리어,예술품,9,9,0.000000,0,0,0,0,0,674145284,674145284,544184202,129961082,155488268,153880451
912348,2017,4,강남구,삼성1동,소매,1001496,유통,전자상거래업,8,8,0.000000,0,0,0,0,0,25637222,25637222,18076747,7560475,9912656,15259305

# 파일 저장

In [ ]:
# df_sorted.to_csv('/content/drive/MyDrive/MC_KDT/프로젝트/파이널프로젝트/데이터/0727_Seoul_preprocessed.csv', encoding='euc-kr')